# Generated by Django 3.2.8 on 2021-10-22 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education_centers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('citizens', '0001_initial'),
        ('organizations', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.IntegerField(blank=True, null=True, verbose_name='ID')),
                ('creation_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания')),
                ('admit_status', models.CharField(choices=[('RECA', 'Заявка получена'), ('CONT', 'Связались/Ждём документы'), ('RECD', 'Получили часть документов'), ('CONF', 'Подтвердили статус'), ('ADM', 'Допустили на платформе'), ('REF', 'Отказали')], default='RECA', max_length=4, verbose_name='Работа с заявкой')),
                ('appl_status', models.CharField(choices=[('NEW', 'Новая заявка'), ('VER', 'Верификация'), ('ADM', 'Допущен'), ('SED', 'Начал обучение'), ('EXAM', 'Направлен на экзамен'), ('COMP', 'Завершил обучение'), ('NCOM', 'Отчислен'), ('NADM', 'Не допущен'), ('RES', 'Резерв'), ('OTH', 'Другой ФО'), ('DUPL', 'Дубликат')], default='NEW', max_length=4, verbose_name='Статус заявки')),
                ('category', models.CharField(choices=[('EMPS', 'Граждане, ищущие работу и обратившиеся в органы службы занятости, включая безработных граждан'), ('JOBS', 'Ищущий работу'), ('UEMP', 'Безработный'), ('VACK', 'Женщины, находящиеся в отпуске по уходу за ребенком в возрасте до трех лет'), ('SCHK', 'Женщины, имеющие детей дошкольного возраста и не состоящие в трудовых отношениях'), ('50+', 'Граждане в возрасте 50-ти лет и старше'), ('SC', 'Граждане предпенсионного возраста')], default='EMPS', max_length=50, verbose_name='Категория слушателя')),
                ('distance_education', models.BooleanField(default=False, verbose_name='Дистанционное обучение')),
                ('contract_type', models.CharField(choices=[('OLD', 'Трехсторонний договор со старым работодателем'), ('NEW', 'Трехсторонний договор с новым работодателем'), ('SELF', 'Двухсторонный договор'), ('NOT', 'Без договора'), ('–', '-')], default='–', max_length=4, verbose_name='Тип контракта')),
                ('ed_ready_time', models.CharField(blank=True, choices=[('CG', 'В планируемой группе'), ('NG', 'В следующей группе'), ('OCT', 'В октябре'), ('NOV', 'В ноябре'), ('NY', 'В следующем году'), ('ALR', 'Уже зачислен')], max_length=4, null=True, verbose_name='Хочет начать учиться')),
                ('consent_pers_data', models.BooleanField(default=False, verbose_name='Согласие на обработку перс. данных')),
                ('pasport', models.BooleanField(default=False, verbose_name='Копия паспорт')),
                ('education_document', models.BooleanField(default=False, verbose_name='Копия документа об образ./справка об обучении')),
                ('resume', models.BooleanField(default=False, verbose_name='Резюме')),
                ('worksearcher_certificate', models.BooleanField(default=False, verbose_name='Справка о регистрации в качестве лица, ищущего работу')),
                ('workbook', models.BooleanField(default=False, verbose_name='Копия трудовой книжки')),
                ('unemployed_certificate', models.BooleanField(default=False, verbose_name='Выписка о регистрации в качестве безработного')),
                ('senior_certificate', models.BooleanField(default=False, verbose_name='Справка об отнесении к категории пред пенсионера')),
                ('parental_leave_confirm', models.BooleanField(default=False, verbose_name='Копия документа, подтверждающего нахождение в отпуске по уходу за ребенком')),
                ('birth_certificate', models.BooleanField(default=False, verbose_name='Копия свидетельства о рождении ребенка')),
                ('birth_certificate_undr_seven', models.BooleanField(default=False, verbose_name='Копия свидетельства о рождении ребенка (младше 7 лет)')),
                ('notIP_certificate', models.BooleanField(default=False, verbose_name='Cправка об отсутствии статуса ИП')),
                ('ib_course', models.BooleanField(default=False, verbose_name='Курсы ИП')),
                ('is_enrolled', models.BooleanField(default=False, verbose_name='Приказ о зачисл.')),
                ('is_deducted', models.BooleanField(default=False, verbose_name='Приказ об отчисл.')),
                ('is_working', models.BooleanField(default=False, verbose_name='Трудоустроен до начала обучения')),
                ('find_work', models.CharField(blank=True, choices=[('CONT', 'Заключил договор'), ('CERT', 'Предоставил справку о самозанятости'), ('VACS', 'Подобраны вакансии'), ('DFI', 'Направлен на собеседование'), ('INTD', 'Прошел собеседование'), ('GAJ', 'Трудоустроился'), ('SWRK', 'Сохранил работу'), ('CRIP', 'Предоставил справку ИП')], max_length=4, null=True, verbose_name='Трудоустройство')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='POE_applications', to='citizens.citizen', verbose_name='Заявитель')),
                ('citizen_consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consulted_applicants', to=settings.AUTH_USER_MODEL, verbose_name='Специалист по работе с клиентами')),
                ('competence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='competence_applicants', to='education_centers.competence', verbose_name='Компетенция')),
                ('education_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='edcenter_applicants', to='education_centers.educationcenter', verbose_name='Центр обучения')),
                ('education_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='programm_applicants', to='education_centers.educationprogram', verbose_name='Програма обучения')),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.company', verbose_name='Работодатель')),
                ('empoyment_specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consulted_citizens', to=settings.AUTH_USER_MODEL, verbose_name='Специалист по трудоустройству')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='education_centers.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Заявка (Содействие занятости)',
                'verbose_name_plural': 'Заявки (Содействие занятости)',
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='anketa', serialize=False, to='federal_empl_program.application')),
                ('convenient_study_periods', models.CharField(blank=True, choices=[('MRNG', '09.00-13.00'), ('DAYT', '13.00-17.00'), ('EVNG', '17.00-21.00')], max_length=4, null=True, verbose_name='Удобное время занятий')),
                ('purpose', models.CharField(blank=True, choices=[('RECA', 'Самозанятость, предпринимательство'), ('CONT', 'Сохранение работы'), ('RECD', 'Поиск новой работы'), ('CONF', 'Саморазвитие')], max_length=4, null=True, verbose_name='Цель')),
                ('need_consultation', models.BooleanField(default=False, verbose_name='Нужна ли консультация по самозаятости')),
                ('pref_contract_type', models.CharField(blank=True, choices=[('OLD', 'Трехсторонний договор со старым работодателем'), ('NEW', 'Трехсторонний договор с новым работодателем'), ('SELF', 'Двухсторонный договор'), ('NOT', 'Без договора')], max_length=4, null=True, verbose_name='Предпочитаемый тип контракта')),
            ],
            options={
                'verbose_name': 'Анкета',
                'verbose_name_plural': 'Анкета',
            },
        ),
        migrations.CreateModel(
            name='InteractionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('interaction_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('comunication_type', models.CharField(choices=[('PHN', 'Телефон'), ('EML', 'Email'), ('OFF', 'Оффлайн')], max_length=3, verbose_name='Канал связи')),
                ('short_description', models.TextField(max_length=2000, verbose_name='Краткое описание')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='federal_empl_program.application', verbose_name='История взаимодействия')),
            ],
            options={
                'verbose_name': 'Взаимодействие с гражданином',
                'verbose_name_plural': 'История взаимодействия',
                'get_latest_by': 'interaction_date',
            },
        ),
    ]
