# Generated by Django 3.2.8 on 2023-07-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Отчество')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, null=True, verbose_name='Пол')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('email', models.EmailField(blank=True, max_length=320, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=40, null=True, verbose_name='Номер телефона')),
                ('education_type', models.CharField(blank=True, choices=[('SPVO', 'Имею диплом о среднем профессиональном или высшем образовании (например, колледжа или вуза)'), ('SCHL', 'Имею среднее образование (школа), в том числе неоконченное'), ('STDN', 'Cтудент')], max_length=4, null=True, verbose_name='Образование')),
                ('employment_status', models.CharField(blank=True, choices=[('MPL', 'Трудоустроен'), ('SMPL', 'Cамозанятый или индивидуальный предприниматель'), ('NMPL', 'Не работаю')], max_length=4, null=True, verbose_name='Трудоустройство')),
                ('planned_employment', models.CharField(blank=True, choices=[('SVMPL', 'Cохранение рабочего места'), ('CMPL', 'Трудоустройство на новую работу'), ('SMPL', 'Открытие или сохранение самозанятости/ИП')], max_length=5, null=True, verbose_name='Трудоустройство')),
            ],
            options={
                'verbose_name': 'Предварительная заявка',
                'verbose_name_plural': 'Предварительные заявки',
            },
        ),
    ]
