# Generated by Django 3.2.5 on 2021-08-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='convenient_study_periods',
            field=models.CharField(blank=True, choices=[('MRNG', '09.00-13.00'), ('DAYT', '13.00-17.00'), ('EVNG', '17.00-21.00')], max_length=4, null=True, verbose_name='Удобное время занятий'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='pref_contract_type',
            field=models.CharField(blank=True, choices=[('OLD', 'Трехсторонний договор со старым работодателем'), ('NEW', 'Трехсторонний договор с новым работодателем'), ('SELF', 'Двухсторонный договор')], max_length=4, null=True, verbose_name='Предпочитаемый тип контракта'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='purpose',
            field=models.CharField(blank=True, choices=[('SWRK', 'Самозанятость, предпринимательство'), ('WORK', 'Сохранение работы'), ('WRKS', 'Поиск новой работы'), ('SDEV', 'Саморазвитие')], max_length=4, null=True, verbose_name='Цель'),
        ),
    ]
