# Generated by Django 3.2.8 on 2023-08-26 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0001_squashed_0006_auto_20230822_1119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EdCenterQuota',
        ),
    ]
