# Generated by Django 3.2.5 on 2021-08-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0002_auto_20210806_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='purpose',
            field=models.CharField(blank=True, choices=[('RECA', 'Самозанятость, предпринимательство'), ('CONT', 'Сохранение работы'), ('RECD', 'Поиск новой работы'), ('CONF', 'Саморазвитие')], max_length=4, null=True, verbose_name='Цель'),
        ),
    ]
