# Generated by Django 3.2.8 on 2023-07-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0002_citizenapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenapplication',
            name='competence',
            field=models.CharField(max_length=250, null=True, verbose_name='Компетенция'),
        ),
        migrations.AddField(
            model_name='citizenapplication',
            name='consultation',
            field=models.BooleanField(default=False, verbose_name='Нужна ли консультация?'),
        ),
        migrations.AddField(
            model_name='citizenapplication',
            name='practice_time',
            field=models.CharField(blank=True, choices=[('MRNG', '9:00-13:00'), ('DAYT', '13:00-17:00'), ('EVNG', '17:00-21:00')], max_length=4, null=True, verbose_name='Удобное время для занятий'),
        ),
    ]
