# Generated by Django 3.2.8 on 2023-08-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0003_auto_20230727_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizenapplication',
            name='consultation',
            field=models.BooleanField(default=False, verbose_name='консультация?'),
        ),
        migrations.AlterField(
            model_name='citizenapplication',
            name='planned_employment',
            field=models.CharField(blank=True, choices=[('SVMPL', 'Cохранение рабочего места'), ('CMPL', 'Трудоустройство на новую работу'), ('SMPL', 'Открытие или сохранение самозанятости/ИП')], max_length=5, null=True, verbose_name='Цель обучения'),
        ),
        migrations.AlterField(
            model_name='citizenapplication',
            name='practice_time',
            field=models.CharField(blank=True, choices=[('MRNG', '9:00-13:00'), ('DAYT', '13:00-17:00'), ('EVNG', '17:00-21:00')], max_length=4, null=True, verbose_name='Удобное время'),
        ),
        migrations.AlterField(
            model_name='educationcenterprojectyear',
            name='stage',
            field=models.CharField(choices=[('FLLNG', 'заполнение'), ('FLLD', 'на проверке'), ('RWRK', 'отправлена на доработку'), ('VRFD', 'проверена'), ('FRMD', 'сформирована'), ('DWNLD', 'подгружена'), ('PRVD', 'принята'), ('FNSHD', 'ПКО пройден')], default='FLLNG', max_length=5, verbose_name='Работа с заявкой'),
        ),
    ]
