# Generated by Django 3.2.8 on 2023-10-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0003_auto_20231005_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='contract_date',
            field=models.DateTimeField(null=True, verbose_name='Дата последней смены статуса'),
        ),
        migrations.AddField(
            model_name='application',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата истечения заявки'),
        ),
        migrations.AlterField(
            model_name='application',
            name='contract_type',
            field=models.CharField(choices=[('OLD', 'Трёхсторонний со старым работодателем'), ('NEW', 'Трёхсторонний с новым работодателем'), ('THR', 'Трёхсторонний'), ('CZN', 'Трёхсторонний с ЦЗН'), ('SELF', 'Двусторонний'), ('NOT', 'Без договора'), ('–', '-')], default='–', max_length=4, verbose_name='Тип контракта'),
        ),
    ]
