# Generated by Django 3.2.5 on 2021-08-14 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0003_alter_questionnaire_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='for_inline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inline_test_models', to='federal_empl_program.application'),
        ),
    ]
