# Generated by Django 3.2.5 on 2021-08-14 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0004_application_for_inline'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_test_models', to='federal_empl_program.application'),
        ),
    ]
