# Generated by Django 3.2.8 on 2023-08-06 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0049_auto_20230616_1519'),
        ('federal_empl_program', '0004_auto_20230806_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdCenterQuotaRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRFT', 'заполнение'), ('LCK', 'на проверке'), ('SND', 'отправлена'), ('PRVD', 'согласована')], default='DRFT', max_length=5, verbose_name='Работа с запросом')),
                ('request_number', models.IntegerField(verbose_name='Номер запроса')),
                ('ed_center_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_requests', to='federal_empl_program.educationcenterprojectyear', verbose_name='Центра обучения (год проекта)')),
            ],
            options={
                'verbose_name': 'Запрос квоты (ЦО)',
                'verbose_name_plural': 'Запрос квоты (ЦО)',
            },
        ),
        migrations.CreateModel(
            name='QuotaRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.IntegerField(verbose_name='Номер запроса')),
                ('status', models.CharField(choices=[('DRFT', 'заполнение'), ('SND', 'отправлена'), ('PRVD', 'согласована')], default='DRFT', max_length=5, verbose_name='Работа с запросом')),
                ('send_date', models.DateField(blank=True, null=True, verbose_name='Дата отправки')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='Дата согласования')),
                ('project_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_requests', to='federal_empl_program.projectyear', verbose_name='Год проекта')),
            ],
            options={
                'verbose_name': 'Запрос квоты',
                'verbose_name_plural': 'Запрос квоты',
            },
        ),
        migrations.CreateModel(
            name='ProgramQuotaRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Стоимость программы')),
                ('req_quota', models.IntegerField(verbose_name='Запращиваемая квота')),
                ('ro_quota', models.IntegerField(verbose_name='Квота (коррекция РО)')),
                ('approved_quota', models.IntegerField(verbose_name='Квота (согласованная)')),
                ('ed_center_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_requests', to='federal_empl_program.edcenterquotarequest', verbose_name='Запрос квоты (ЦО)')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_requests', to='education_centers.educationprogram', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Запрос квоты (программа)',
                'verbose_name_plural': 'Запрос квоты (программы)',
            },
        ),
        migrations.AddField(
            model_name='edcenterquotarequest',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centers_requests', to='federal_empl_program.quotarequest', verbose_name='Запрос квоты'),
        ),
    ]
