# Generated by Django 4.2 on 2023-10-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0005_auto_20231011_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectyear',
            name='appls_last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего обновления заявок'),
        ),
    ]
