# Generated by Django 3.2.8 on 2023-08-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0005_auto_20230806_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programquotarequest',
            name='approved_quota',
            field=models.IntegerField(default=0, verbose_name='Квота (согласованная)'),
        ),
        migrations.AlterField(
            model_name='programquotarequest',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Стоимость программы'),
        ),
        migrations.AlterField(
            model_name='programquotarequest',
            name='req_quota',
            field=models.IntegerField(default=0, verbose_name='Запращиваемая квота'),
        ),
        migrations.AlterField(
            model_name='programquotarequest',
            name='ro_quota',
            field=models.IntegerField(default=0, verbose_name='Квота (коррекция РО)'),
        ),
    ]
