# Generated by Django 3.2.5 on 2021-08-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0006_auto_20210816_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('OLD', 'Трехсторонний договор со старым работодателем'), ('NEW', 'Трехсторонний договор с новым работодателем'), ('SELF', 'Двухсторонный договор')], max_length=4, null=True, verbose_name='Тип контракта'),
        ),
    ]
