# Generated by Django 4.2 on 2023-10-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0006_projectyear_appls_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectyear',
            name='full_budget',
            field=models.IntegerField(default=49850840, verbose_name='Бюджет'),
        ),
        migrations.AddField(
            model_name='projectyear',
            name='price_144',
            field=models.IntegerField(default=40920, verbose_name='Стоимость 144'),
        ),
        migrations.AddField(
            model_name='projectyear',
            name='price_256',
            field=models.IntegerField(default=61380, verbose_name='Стоимость 256'),
        ),
        migrations.AddField(
            model_name='projectyear',
            name='price_72',
            field=models.IntegerField(default=27435, verbose_name='Стоимость 72'),
        ),
    ]
