# Generated by Django 3.2.5 on 2021-08-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0007_alter_application_contract_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='contract_type',
            field=models.CharField(choices=[('OLD', 'Трехсторонний договор со старым работодателем'), ('NEW', 'Трехсторонний договор с новым работодателем'), ('SELF', 'Двухсторонный договор')], default='SELF', max_length=4, verbose_name='Тип контракта'),
        ),
    ]
