# Generated by Django 4.2 on 2023-10-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0007_projectyear_full_budget_projectyear_price_144_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Стоимость обучения'),
        ),
    ]
