# Generated by Django 3.2.5 on 2021-08-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0009_alter_application_contract_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interactionhistory',
            options={'get_latest_by': 'interaction_date', 'verbose_name': 'Взаимодействие с гражданином', 'verbose_name_plural': 'История взаимодействия'},
        ),
        migrations.AddField(
            model_name='application',
            name='ed_ready_time',
            field=models.CharField(blank=True, choices=[('CG', 'В планируемой группе'), ('NG', 'В следующей группе'), ('OCT', 'В октябре'), ('NOV', 'В ноябре'), ('NY', 'В следующем году'), ('ALR', 'Уже зачислен')], max_length=4, null=True, verbose_name='Хочет начать учиться'),
        ),
    ]
