# Generated by Django 4.2 on 2023-11-30 07:09

from django.db import migrations, models
import django.db.models.deletion
import federal_empl_program.models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0009_alter_educationprogram_period'),
        ('federal_empl_program', '0009_application_added_to_act'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('ACT', 'Акт'), ('RPRT', 'Отчёт об трудоустройсте')], max_length=4, verbose_name='Тип документа')),
                ('doc_file', models.FileField(upload_to=federal_empl_program.models.ClosingDocument.doc_path, verbose_name='Акт/Отчёт')),
                ('bill_file', models.FileField(upload_to=federal_empl_program.models.ClosingDocument.bill_path, verbose_name='Счёт')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closing_documents', to='education_centers.group', verbose_name='Поток')),
            ],
            options={
                'verbose_name': 'Закрывающий документ',
                'verbose_name_plural': 'Закрывающие документы',
            },
        ),
    ]
