# Generated by Django 4.2 on 2023-11-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0010_closingdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='closingdocument',
            name='bill_sum',
            field=models.IntegerField(default=0, verbose_name='Сумма оплаты'),
        ),
        migrations.AddField(
            model_name='closingdocument',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплаченно?'),
        ),
    ]
