# Generated by Django 3.2.5 on 2021-08-21 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0010_auto_20210820_1104'),
        ('federal_empl_program', '0010_auto_20210819_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.CharField(choices=[('EMPS', 'Граждане, ищущие работу и обратившиеся в органы службы занятости, включая безработных граждан'), ('JOBS', 'Ищущий работу'), ('UEMP', 'Безработный'), ('VACK', 'Женщины, находящиеся в отпуске по уходу за ребенком в возрасте до трех лет'), ('SCHK', 'Женщины, имеющие детей дошкольного возраста и не состоящие в трудовых отношениях'), ('50+', 'Граждане в возрасте 50-ти лет и старше'), ('SC', 'Граждане предпенсионного возраста')], default='EMPS', max_length=50, verbose_name='Категория слушателя'),
        ),
        migrations.AlterField(
            model_name='application',
            name='education_program',
            field=models.ForeignKey(blank=True, limit_choices_to={'competence': models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='competence_applicants', to='education_centers.competence', verbose_name='Компетенция')}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='programm_applicants', to='education_centers.educationprogram', verbose_name='Програма обучения'),
        ),
    ]
