# Generated by Django 4.2.6 on 2023-12-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0011_closingdocument_bill_sum_closingdocument_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='closingdocument',
            name='bill_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата в счёте'),
        ),
    ]
