# Generated by Django 4.2.6 on 2023-12-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0013_remove_closingdocument_bill_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closingdocument',
            name='bill_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер счёта'),
        ),
    ]
