# Generated by Django 4.2.6 on 2023-12-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0014_alter_closingdocument_bill_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='is_working',
            field=models.BooleanField(default=False, verbose_name='Трудоустроен (не подтверждено)'),
        ),
        migrations.AlterField(
            model_name='flowstatus',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='flowstatus',
            name='off_name',
            field=models.CharField(max_length=300, verbose_name='Название с flow'),
        ),
    ]
