# Generated by Django 3.2.5 on 2021-09-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0014_alter_application_education_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='contract_type',
            field=models.CharField(choices=[('OLD', 'Трехсторонний договор со старым работодателем'), ('NEW', 'Трехсторонний договор с новым работодателем'), ('SELF', 'Двухсторонный договор'), ('NOT', 'Без договора'), ('–', '-')], default='–', max_length=4, verbose_name='Тип контракта'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='pref_contract_type',
            field=models.CharField(blank=True, choices=[('OLD', 'Трехсторонний договор со старым работодателем'), ('NEW', 'Трехсторонний договор с новым работодателем'), ('SELF', 'Двухсторонный договор'), ('NOT', 'Без договора')], max_length=4, null=True, verbose_name='Предпочитаемый тип контракта'),
        ),
    ]
