# Generated by Django 4.2.6 on 2023-12-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0015_alter_application_is_working_alter_flowstatus_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closingdocument',
            name='bill_sum',
            field=models.FloatField(default=0, verbose_name='Сумма оплаты'),
        ),
        migrations.AlterField(
            model_name='flowstatus',
            name='name',
            field=models.CharField(max_length=700, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='flowstatus',
            name='off_name',
            field=models.CharField(max_length=700, verbose_name='Название с flow'),
        ),
    ]
