# Generated by Django 4.2.6 on 2023-12-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0016_alter_closingdocument_bill_sum_alter_flowstatus_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizencategory',
            name='official_name',
            field=models.CharField(blank=True, max_length=600, verbose_name='Офицальное наименованние'),
        ),
    ]
