# Generated by Django 4.2.6 on 2023-12-23 13:51

from django.db import migrations, models
import django.db.models.deletion
import federal_empl_program.models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0018_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер счёта')),
                ('amount', models.FloatField(default=0, verbose_name='Сумма оплаты')),
                ('invoice_file', models.FileField(upload_to=federal_empl_program.models.EmploymentInvoice.invoice_path, verbose_name='Счёт')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empl_invoices', to='federal_empl_program.contract', verbose_name='договор')),
            ],
            options={
                'verbose_name': 'Счёт (30%)',
                'verbose_name_plural': 'Счёта (30%)',
            },
        ),
    ]
