# Generated by Django 4.2.6 on 2023-12-24 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0019_employmentinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='applications', to='federal_empl_program.contract', verbose_name='Договор'),
        ),
        migrations.AddField(
            model_name='application',
            name='employment_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='applications', to='federal_empl_program.employmentinvoice', verbose_name='Счёт (30%)'),
        ),
    ]
