# Generated by Django 4.2.6 on 2023-12-24 16:55

from django.db import migrations, models
import federal_empl_program.models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0020_application_contract_application_employment_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentinvoice',
            name='invoice_file',
            field=models.FileField(blank=True, upload_to=federal_empl_program.models.EmploymentInvoice.invoice_path, verbose_name='Счёт'),
        ),
    ]
