# Generated by Django 4.2.6 on 2023-12-24 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0021_alter_employmentinvoice_invoice_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='employment_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='federal_empl_program.employmentinvoice', verbose_name='Счёт (30%)'),
        ),
    ]
