# Generated by Django 4.2.6 on 2023-12-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0024_employmentinvoice_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentinvoice',
            name='is_requisted',
            field=models.BooleanField(default=False, verbose_name='Запросили счёт'),
        ),
    ]
