# Generated by Django 4.2.6 on 2024-01-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0025_employmentinvoice_is_requisted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='added_to_act',
            field=models.BooleanField(default=False, verbose_name='Актирован'),
        ),
    ]
