# Generated by Django 4.2.6 on 2024-02-14 08:23

from django.db import migrations, models
import django.db.models.deletion
import federal_empl_program.models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0026_alter_application_added_to_act'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationcenterprojectyear',
            name='stage',
            field=models.CharField(choices=[('FLLNG', 'заполнение'), ('FLLD', 'на проверке'), ('RWRK', 'отправлен на доработку'), ('VRFD', 'проверен'), ('FRMD', 'договор сформирован'), ('DWNLD', 'договор подгружен'), ('PRVD', 'договор подписан'), ('FNSHD', 'ПКО пройден')], default='FLLNG', max_length=5, verbose_name='Работа с заявкой'),
        ),
        migrations.CreateModel(
            name='NetworkAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_number', models.IntegerField(default=1, verbose_name='№ цикла')),
                ('stage', models.CharField(choices=[('FLLNG', 'заполнение'), ('DWNLD', 'договор подгружен'), ('PRVD', 'договор подписан')], default='FLLNG', max_length=5, verbose_name='Статус договора')),
                ('agreement_file', models.FileField(upload_to=federal_empl_program.models.NetworkAgreement.agreement_path, verbose_name='Договор')),
                ('project_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='net_agreements', to='federal_empl_program.projectyear', verbose_name='Год проекта')),
            ],
            options={
                'verbose_name': 'Сетевой договор',
                'verbose_name_plural': 'Сетевые договоры',
            },
        ),
    ]
