# Generated by Django 4.2.6 on 2024-02-14 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0027_alter_educationcenterprojectyear_stage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkagreement',
            name='project_year',
        ),
        migrations.AddField(
            model_name='networkagreement',
            name='ed_center_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='net_agreements', to='federal_empl_program.educationcenterprojectyear', verbose_name='Центра обучения (год проекта)'),
            preserve_default=False,
        ),
    ]
