# Generated by Django 4.2.6 on 2024-02-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0019_teacher_consent_file'),
        ('federal_empl_program', '0030_networkagreement_ed_center_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkagreement',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='new_agreements', to='education_centers.educationprogram', verbose_name='Программы'),
        ),
    ]
