# Generated by Django 4.2.6 on 2024-02-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0031_networkagreement_programs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkagreement',
            name='agreement_number',
            field=models.IntegerField(default=0, verbose_name='№ цикла'),
        ),
    ]
