# Generated by Django 4.2.6 on 2024-02-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0032_alter_networkagreement_agreement_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkagreement',
            name='suffix',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Доп. номер'),
        ),
    ]
