# Generated by Django 4.2.6 on 2024-02-26 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0019_teacher_consent_file'),
        ('federal_empl_program', '0033_networkagreement_suffix'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Код')),
                ('name', models.CharField(max_length=350, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Компетенция (Вид деятельности)',
                'verbose_name_plural': 'Компетенции (Виды деятельности)',
            },
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='Номер')),
                ('name', models.CharField(max_length=350, verbose_name='вид деятельности')),
            ],
            options={
                'verbose_name': 'Вид деятельности',
                'verbose_name_plural': 'Виды деятельности',
            },
        ),
        migrations.CreateModel(
            name='FgosStandart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код ПС')),
                ('name', models.CharField(max_length=350, verbose_name='Наименование стандарта')),
                ('standart_type', models.CharField(blank=True, choices=[('VO', 'ФГОС ВО'), ('SPO', 'ФГОС СПО')], max_length=4, null=True, verbose_name='Тип стандарта')),
                ('prof_field', models.CharField(max_length=350, verbose_name='Область профессиональной деятельности')),
            ],
            options={
                'verbose_name': 'ФГОС Стандарт',
                'verbose_name_plural': 'ФГОС Стандарты',
            },
        ),
        migrations.CreateModel(
            name='IrpoProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование программы')),
                ('assigned_qualif', models.CharField(blank=True, max_length=250, null=True, verbose_name='Присваиваемая квалификация')),
                ('prof_field', models.CharField(blank=True, max_length=250, null=True, verbose_name='Вид профессиональной деятельности')),
                ('category_name', models.CharField(max_length=250, verbose_name='Категория слушателей')),
                ('program_type', models.CharField(blank=True, choices=[('DPOPK', 'ДПО ПК'), ('DPOPP', 'ДПО ПП'), ('POP', 'ПО П'), ('POPP', 'ПО ПП'), ('POPK', 'ПО ПК')], max_length=5, null=True, verbose_name='Тип программы')),
                ('education_form', models.CharField(blank=True, choices=[('FLL', 'Очная'), ('PRTLN', 'Очно-заочная'), ('PRT', 'Заочная')], max_length=5, null=True, verbose_name='Форма обучения')),
                ('status', models.CharField(choices=[(0, 'Создана'), (1, '1. Общие сведения о программе'), (2, '2. Планируемые результаты обучения'), (3, '3. Учебно-тематический план'), (4, '4. Календарный учебный график'), (5, '6. Материально-техническое обеспечение'), (6, '6. Информационное и учебно-методическое обеспечение')], default=0, max_length=5, verbose_name='Статус')),
                ('gen_functions', models.TextField(verbose_name='Обобщенные (конкретные) трудовые функции')),
                ('qual_level', models.CharField(blank=True, max_length=20, null=True, verbose_name='Уровень квалификации в соответствии с профессиональным стандартом')),
                ('training_schedule', models.JSONField(blank=True, null=True, verbose_name='Календарный учебный график')),
            ],
            options={
                'verbose_name': 'Программа (ИРПО)',
                'verbose_name_plural': 'Программы (ИРПО)',
            },
        ),
        migrations.CreateModel(
            name='Profstandart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код ПС')),
                ('name', models.CharField(max_length=350, verbose_name='Наименование стандарта')),
            ],
            options={
                'verbose_name': 'Нормативно-правовой документ',
                'verbose_name_plural': 'Нормативно-правовые документы',
            },
        ),
        migrations.CreateModel(
            name='ProgramModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='Номер')),
                ('name', models.CharField(max_length=350, verbose_name='Наименование')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='federal_empl_program.irpoprogram', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Учебный модуль',
                'verbose_name_plural': 'Учебные модули',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='Номер')),
                ('name', models.CharField(max_length=350, verbose_name='Наименование')),
                ('lections_duration', models.IntegerField(default=0, verbose_name='Лекции (ак. часы)')),
                ('practice_duration', models.IntegerField(default=0, verbose_name='Практика (ак. часы)')),
                ('consultations_duration', models.IntegerField(default=0, verbose_name='Консультации (ак. часы)')),
                ('independent_duration', models.IntegerField(default=0, verbose_name='Самостоятельная работа (ак. часы)')),
                ('lections', models.CharField(blank=True, max_length=500, null=True, verbose_name='Лекции (содержание)')),
                ('practice', models.CharField(blank=True, default=0, max_length=500, null=True, verbose_name='Практика (содержание)')),
                ('consultations', models.CharField(blank=True, default=0, max_length=500, null=True, verbose_name='Консультации (содержание)')),
                ('independent', models.CharField(blank=True, default=0, max_length=500, null=True, verbose_name='Самостоятельная работа (содержание)')),
                ('attest_form', models.CharField(blank=True, max_length=100, null=True, verbose_name='Форма аттестации')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='federal_empl_program.programmodule', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Учебный модуль',
                'verbose_name_plural': 'Учебные модули',
            },
        ),
        migrations.CreateModel(
            name='RegulatoryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350, verbose_name='Наименование программы')),
                ('ed_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_docs', to='federal_empl_program.educationcenterprojectyear', verbose_name='ЦО')),
            ],
            options={
                'verbose_name': 'Нормативно-правовой документ',
                'verbose_name_plural': 'Нормативно-правовые документы',
            },
        ),
        migrations.CreateModel(
            name='ProgramDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350, verbose_name='Наименование')),
                ('doc_type', models.CharField(blank=True, choices=[('LAW', 'Нормативные правовые акты, иная документация'), ('MAIN', 'Основная литература'), ('ADD', 'Дополнительная литература'), ('INT', 'Интернет-ресурсы'), ('LIB', 'Электронно-библиотечная система')], max_length=5, null=True, verbose_name='Тип документации')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentation', to='federal_empl_program.irpoprogram', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Документация',
                'verbose_name_plural': 'Документация',
            },
        ),
        migrations.AddField(
            model_name='irpoprogram',
            name='profstandarts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irpo_programs', to='federal_empl_program.profstandart', verbose_name='Профстандарты'),
        ),
        migrations.AddField(
            model_name='irpoprogram',
            name='standart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irpo_programs', to='federal_empl_program.fgosstandart', verbose_name='Стандарт (СПО/ВО)'),
        ),
        migrations.AddField(
            model_name='irpoprogram',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='irpo_programs', to='education_centers.teacher', verbose_name='Разработчики'),
        ),
        migrations.CreateModel(
            name='ActivityCompetenceIndicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='Номер')),
                ('knowledge', models.CharField(max_length=350, verbose_name='Знание')),
                ('skill', models.CharField(max_length=350, verbose_name='Умение')),
                ('practice', models.CharField(blank=True, max_length=350, null=True, verbose_name='Практический опты')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='federal_empl_program.activitycompetence', verbose_name='Профстандарты')),
            ],
            options={
                'verbose_name': 'Показатель (компетенция)',
                'verbose_name_plural': 'Показатели (компетенции)',
            },
        ),
        migrations.CreateModel(
            name='ActivityCompetenceEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350, verbose_name='Наименование')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='federal_empl_program.activitycompetence', verbose_name='Профстандарты')),
            ],
            options={
                'verbose_name': 'МТБ',
                'verbose_name_plural': 'МТБ',
            },
        ),
        migrations.AddField(
            model_name='activitycompetence',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='federal_empl_program.activitytype', verbose_name='Вид деятельности'),
        ),
    ]
