# Generated by Django 4.2.6 on 2024-02-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0034_activitycompetence_activitytype_fgosstandart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycompetenceindicators',
            name='practice',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Практический опыт'),
        ),
    ]
