# Generated by Django 4.2.6 on 2024-03-02 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0021_alter_educationprogram_employer_review_and_more'),
        ('federal_empl_program', '0035_alter_activitycompetenceindicators_practice'),
    ]

    operations = [
        migrations.AddField(
            model_name='irpoprogram',
            name='ed_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='irpo_programs', to='education_centers.educationprogram', verbose_name='Программа'),
        ),
        migrations.AlterField(
            model_name='irpoprogram',
            name='category_name',
            field=models.CharField(max_length=250, null=True, verbose_name='Категория слушателей'),
        ),
        migrations.AlterField(
            model_name='irpoprogram',
            name='gen_functions',
            field=models.TextField(blank=True, null=True, verbose_name='Обобщенные (конкретные) трудовые функции'),
        ),
        migrations.AlterField(
            model_name='irpoprogram',
            name='profstandarts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='irpo_programs', to='federal_empl_program.profstandart', verbose_name='Профстандарты'),
        ),
        migrations.AlterField(
            model_name='irpoprogram',
            name='standart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='irpo_programs', to='federal_empl_program.fgosstandart', verbose_name='Стандарт (СПО/ВО)'),
        ),
        migrations.AlterField(
            model_name='irpoprogram',
            name='status',
            field=models.CharField(blank=True, choices=[(0, 'Создана'), (1, '1. Общие сведения о программе'), (2, '2. Планируемые результаты обучения'), (3, '3. Учебно-тематический план'), (4, '4. Календарный учебный график'), (5, '6. Материально-техническое обеспечение'), (6, '6. Информационное и учебно-методическое обеспечение')], default=0, max_length=5, null=True, verbose_name='Статус'),
        ),
    ]
