# Generated by Django 4.2.6 on 2024-03-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0037_irpoprogram_ed_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='irpoprogram',
            name='duration',
            field=models.IntegerField(blank=True, default=1, verbose_name='Длительность (ак. часов)'),
            preserve_default=False,
        ),
    ]
