# Generated by Django 4.2.6 on 2024-03-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0039_proffield_alter_irpoprogram_education_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='irpoprogram',
            name='prof_activity_type',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Вид профессиональной деятельности'),
        ),
    ]
