# Generated by Django 4.2.6 on 2024-03-03 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0040_irpoprogram_prof_activity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irpoprogram',
            name='profstandarts',
        ),
        migrations.AddField(
            model_name='irpoprogram',
            name='profstandart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='irpo_programs', to='federal_empl_program.profstandart', verbose_name='Профстандарт'),
        ),
    ]
