# Generated by Django 4.2.6 on 2024-03-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0044_alter_profstandart_prof_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profstandart',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование стандарта'),
        ),
        migrations.AlterField(
            model_name='profstandart',
            name='prof_activity_type',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Вид профессиональной деятельности'),
        ),
    ]
