# Generated by Django 4.2.6 on 2024-03-03 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0046_alter_profstandart_prof_activity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fgosstandart',
            name='prof_field',
        ),
    ]
