# Generated by Django 4.2.6 on 2024-03-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0049_alter_irpoprogram_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='irpoprogram',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='irpo_programs', to='federal_empl_program.activitytype', verbose_name='Виды деятельности'),
        ),
        migrations.AlterField(
            model_name='irpoprogram',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Шаг 1. Общие сведения о программе'), ('2', 'Шаг 2. Планируемые результаты обучения'), ('3', 'Шаг 3. Разработчики (составители)'), ('4', 'Шаг 4. Учебно-тематический план'), ('5', 'Шаг 5. Календарный учебный график'), ('6', 'Шаг 6. Материально-техническое обеспечение'), ('7', 'Шаг 7. Информационное и учебно-методическое обеспечение')], default='1', max_length=5, null=True, verbose_name='Статус'),
        ),
    ]
