# Generated by Django 4.2.6 on 2024-03-03 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0050_irpoprogram_activities_alter_irpoprogram_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irpoprogram',
            name='activities',
        ),
        migrations.AddField(
            model_name='activitytype',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='federal_empl_program.irpoprogram', verbose_name='Программа'),
            preserve_default=False,
        ),
    ]
