# Generated by Django 4.2.6 on 2024-03-04 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0021_alter_educationprogram_employer_review_and_more'),
        ('federal_empl_program', '0053_author_remove_irpoprogram_teachers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='ed_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='education_centers.educationcenter', verbose_name='Центр обучения'),
        ),
    ]
