# Generated by Django 4.2.6 on 2024-03-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0055_alter_subject_options_alter_subject_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='consultations',
            field=models.TextField(blank=True, default=0, null=True, verbose_name='Консультации (содержание)'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='independent',
            field=models.TextField(blank=True, default=0, null=True, verbose_name='Самостоятельная работа (содержание)'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='lections',
            field=models.TextField(blank=True, null=True, verbose_name='Лекции (содержание)'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='practice',
            field=models.TextField(blank=True, default=0, null=True, verbose_name='Практика (содержание)'),
        ),
    ]
