# Generated by Django 4.2.6 on 2024-03-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0056_alter_subject_consultations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='irpoprogram',
            name='exam_attest_form',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Форма итоговой аттестации'),
        ),
        migrations.AddField(
            model_name='irpoprogram',
            name='exam_consultations_duration',
            field=models.IntegerField(default=0, verbose_name='Консультации (ИА)'),
        ),
        migrations.AddField(
            model_name='irpoprogram',
            name='exam_independent_duration',
            field=models.IntegerField(default=0, verbose_name='Самостоятельная работа (ИА)'),
        ),
        migrations.AddField(
            model_name='irpoprogram',
            name='exam_lections_duration',
            field=models.IntegerField(default=0, verbose_name='Лекции (ИА)'),
        ),
        migrations.AddField(
            model_name='irpoprogram',
            name='exam_practice_duration',
            field=models.IntegerField(default=0, verbose_name='Практика (ИА)'),
        ),
        migrations.AddField(
            model_name='programmodule',
            name='attest_form',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Форма аттестации'),
        ),
        migrations.AddField(
            model_name='programmodule',
            name='consultations_duration',
            field=models.IntegerField(default=0, verbose_name='Консультации (ак. часы)'),
        ),
        migrations.AddField(
            model_name='programmodule',
            name='independent_duration',
            field=models.IntegerField(default=0, verbose_name='Самостоятельная работа (ак. часы)'),
        ),
        migrations.AddField(
            model_name='programmodule',
            name='lections_duration',
            field=models.IntegerField(default=0, verbose_name='Лекции (ак. часы)'),
        ),
        migrations.AddField(
            model_name='programmodule',
            name='practice_duration',
            field=models.IntegerField(default=0, verbose_name='Практика (ак. часы)'),
        ),
    ]
