# Generated by Django 4.2.6 on 2024-03-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0057_irpoprogram_exam_attest_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='irpoprogram',
            name='duration_days',
            field=models.IntegerField(blank=True, default=1, verbose_name='Период освоения'),
            preserve_default=False,
        ),
    ]
