# Generated by Django 4.2.6 on 2024-03-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0058_irpoprogram_duration_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irpoprogram',
            name='duration_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Период освоения'),
        ),
    ]
