# Generated by Django 4.2.6 on 2024-03-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0060_irpoprogram_current_control_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitycompetenceequipment',
            name='competence',
        ),
        migrations.AddField(
            model_name='activitycompetenceequipment',
            name='competencies',
            field=models.ManyToManyField(related_name='equipment', to='federal_empl_program.activitycompetence', verbose_name='Профстандарты'),
        ),
    ]
