# Generated by Django 4.2.6 on 2024-03-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0061_remove_activitycompetenceequipment_competence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycompetenceequipment',
            name='name',
            field=models.TextField(verbose_name='Наименование'),
        ),
    ]
