# Generated by Django 4.2.6 on 2024-03-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0062_alter_activitycompetenceequipment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycompetenceequipment',
            name='competencies',
            field=models.ManyToManyField(related_name='equipments', to='federal_empl_program.activitycompetence', verbose_name='Профстандарты'),
        ),
    ]
