# Generated by Django 4.2.6 on 2024-03-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0064_profstandart_mintrud_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irpoprogram',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Шаг 1. Общие сведения о программе'), ('2', 'Шаг 2. Планируемые результаты обучения'), ('3', 'Шаг 3. Разработчики (составители)'), ('4', 'Шаг 4. Учебно-тематический план'), ('5', 'Шаг 5. Календарный учебный график'), ('6', 'Шаг 5. Информационное и учебно-методическое обеспечение')], default='1', max_length=5, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='profstandart',
            name='mintrud_order_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Приказ Минтруда России (дата)'),
        ),
        migrations.AlterField(
            model_name='profstandart',
            name='mintrud_order_number',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Приказ Минтруда России\t(номер)'),
        ),
        migrations.AlterField(
            model_name='profstandart',
            name='minust_order_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Приказ Минюста России (дата)'),
        ),
        migrations.AlterField(
            model_name='profstandart',
            name='minust_order_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Приказ Минюста России\t(номер)'),
        ),
    ]
