# Generated by Django 4.2.6 on 2024-03-15 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0065_remove_irpoprogram_category_name_and_more'),
    ]

    operations = [

    ]
