# Generated by Django 4.2.6 on 2024-03-15 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0066_remove_irpoprogram_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irpoprogram',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='irpoprogram',
            name='training_schedule',
        ),
    ]
