# Generated by Django 4.2.6 on 2024-03-19 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0066_remove_irpoprogram_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_count', models.IntegerField(default=0, verbose_name='Планируется обучить')),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='federal_empl_program.irpoprogram', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'План обучения по программе',
                'verbose_name_plural': 'Планы обучения по программам',
            },
        ),
        migrations.CreateModel(
            name='MonthProgramPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('5', 'Май'), ('6', 'Июнь'), ('7', 'Июль'), ('8', 'Август'), ('9', 'Сентябрь'), ('10', 'Октябрь'), ('11', 'Ноябрь')], max_length=5, verbose_name='Месяц')),
                ('students_count', models.IntegerField(default=0, verbose_name='Планируется обучить')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_plans', to='federal_empl_program.programplan', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'План обучения на месяц',
                'verbose_name_plural': 'Планы обучения на месяц',
            },
        ),
    ]
