# Generated by Django 4.2.6 on 2024-03-21 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0025_alter_educationprogram_employer_review_and_more'),
        ('federal_empl_program', '0067_programplan_monthprogramplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programplan',
            name='program',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='education_centers.educationprogram', verbose_name='Программа'),
        ),
    ]
