# Generated by Django 4.2.6 on 2024-03-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0068_alter_programplan_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmodule',
            name='exam_consultations',
            field=models.TextField(blank=True, null=True, verbose_name='Консультации (ПА)'),
        ),
        migrations.AddField(
            model_name='programmodule',
            name='exam_independent',
            field=models.TextField(blank=True, null=True, verbose_name='Самостоятельная работа (ПА)'),
        ),
        migrations.AddField(
            model_name='programmodule',
            name='exam_lections',
            field=models.TextField(blank=True, null=True, verbose_name='Лекции (ПА)'),
        ),
        migrations.AddField(
            model_name='programmodule',
            name='exam_practice',
            field=models.TextField(blank=True, null=True, verbose_name='Практика (ПА)'),
        ),
    ]
