# Generated by Django 4.2.6 on 2024-03-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0069_programmodule_exam_consultations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irpoprogram',
            name='exam_consultations_duration',
        ),
        migrations.RemoveField(
            model_name='irpoprogram',
            name='exam_independent_duration',
        ),
        migrations.RemoveField(
            model_name='irpoprogram',
            name='exam_lections_duration',
        ),
        migrations.RemoveField(
            model_name='irpoprogram',
            name='exam_practice_duration',
        ),
        migrations.AddField(
            model_name='irpoprogram',
            name='exam_duration',
            field=models.IntegerField(default=0, verbose_name='длительность ИА'),
        ),
    ]
