# Generated by Django 4.2.6 on 2024-07-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0072_alter_citizenapplication_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='atlas_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Статус в Атлас'),
        ),
        migrations.AddField(
            model_name='application',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='Окончание периода обучения'),
        ),
        migrations.AddField(
            model_name='application',
            name='rvr_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Статус в РвР'),
        ),
        migrations.AddField(
            model_name='application',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='Начало периода обучения'),
        ),
    ]
