# Generated by Django 4.2.6 on 2024-07-04 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0073_application_atlas_status_application_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='application',
            name='start_date',
        ),
    ]
