# Generated by Django 4.2.6 on 2024-07-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0074_remove_application_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='atlas_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер заявления на РР'),
        ),
    ]
