# Generated by Django 4.2.6 on 2024-07-08 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0076_applstatus_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applstatus',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Очередь'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application', to='federal_empl_program.applstatus', verbose_name='Статус'),
        ),
    ]
