# Generated by Django 3.2.8 on 2023-08-25 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisabilityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ОВЗ')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Инвалидность',
                'verbose_name_plural': 'Инвалидности',
            },
        ),
        migrations.AlterField(
            model_name='mailattachfile',
            name='upload_date_time',
            field=models.DateTimeField(verbose_name='Дата и время загрузки'),
        ),
        migrations.AlterField(
            model_name='partnercontact',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='пользователь', to=settings.AUTH_USER_MODEL),
        ),
    ]
