# Generated by Django 4.2 on 2023-11-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230825_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('CTZ', 'Гражданин'), ('CO', 'Представитель ЦО'), ('COR', 'Координатор'), ('BLM', 'Участник Абилимпикса')], max_length=3, null=True, verbose_name='Роль'),
        ),
    ]
