# Generated by Django 4.2 on 2023-12-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('CTZ', 'Гражданин'), ('CO', 'Представитель ЦО'), ('COR', 'Координатор'), ('BLM', 'Участник Абилимпикса'), ('CNT', 'Бухгалтер')], max_length=3, null=True, verbose_name='Роль'),
        ),
    ]
