# Generated by Django 4.2.6 on 2024-01-27 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_partnercontact_projects_delete_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnercontact',
            name='organization',
        ),
        migrations.DeleteModel(
            name='PartnerOrganization',
        ),
    ]
