# Generated by Django 4.2.6 on 2024-01-27 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_partnercontact_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnercontactemail',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='partnercontactphone',
            name='contact',
        ),
    ]
