# Generated by Django 4.2.6 on 2024-01-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_partnercontactemail_contact_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartnerContact',
        ),
    ]
