# Generated by Django 4.2.6 on 2024-01-27 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_mailattachfile_attached_file_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartnerContactEmail',
        ),
    ]
