# Generated by Django 4.2.6 on 2024-01-27 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_delete_partnercontactemail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartnerContactPhone',
        ),
    ]
