# Generated by Django 4.2.6 on 2024-01-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_remove_contactpersone_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название организации'),
        ),
    ]
