# Generated by Django 3.2.5 on 2021-09-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_vacancy_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=50, verbose_name='Название компании'),
        ),
    ]
