# Generated by Django 3.2.5 on 2021-07-29 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, null=True, verbose_name='Пол')),
                ('email', models.EmailField(blank=True, max_length=320, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='Номер телефона')),
                ('snils_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='Номер СНИЛС')),
                ('inn_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='ИНН')),
                ('res_region', models.CharField(blank=True, max_length=50, null=True, verbose_name='Регион проживания')),
                ('res_city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Населённый пункт')),
                ('res_disctrict', models.CharField(blank=True, max_length=50, null=True, verbose_name='Населённый пункт')),
                ('social_status', models.CharField(blank=True, choices=[('SCHS', 'Обучающиеся общеообразовательных организаций'), ('SSPO', 'Студент СПО'), ('SVO', 'Студент ВО'), ('EMP', 'Cотрудник предприятия'), ('SC', 'Гражданин предпенсионного возраста'), ('50+', 'Гражданин старше 50-ти лет'), ('UEMP', 'Безработный гражданин (статус ЦЗН)'), ('EMPS', 'Гражданин, ищущий работу (статус ЦЗН)'), ('OTHR', 'Другой')], max_length=4, null=True, verbose_name='Социальный статус')),
                ('education_type', models.CharField(blank=True, choices=[('SPO', 'Среднее профессиональное'), ('VO', 'Высшее'), ('SSPO', 'Cтудент ВО'), ('SVO', 'Cтудент СПО'), ('11', '11 классов'), ('9', '9 классов'), ('OTHR', 'Другой')], max_length=4, null=True, verbose_name='Образование')),
                ('self_employed', models.BooleanField(default=False, verbose_name='Самозанятый')),
                ('is_employed', models.BooleanField(default=False, verbose_name='Трудоустроен')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Верифицирован')),
            ],
            options={
                'verbose_name': 'Гражданин',
                'verbose_name_plural': 'Граждани',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50, verbose_name='Должность')),
                ('start_date', models.DateField(verbose_name='Дата начала работы')),
                ('end_date', models.DateField(verbose_name='Дата окончания работы')),
                ('place_of_work', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employees', to='organizations.company', verbose_name='Место работы')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='citizens.citizen')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
    ]
