# Generated by Django 3.2.5 on 2021-08-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='copp_registration',
            field=models.BooleanField(default=False, verbose_name='Зарегистрирован на copp63.ru'),
        ),
    ]
