# Generated by Django 3.2.8 on 2023-03-30 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('education_centers', '0003_auto_20230330_1206'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('citizens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='disability_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='citizens.disabilitytype', verbose_name='ОВЗ'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='ed_center_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citizens', to='education_centers.educationcentergroup', verbose_name='Предварительная заявка'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='citizens.school', verbose_name='Школа'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='citizens.schoolclass', verbose_name='Школный класс'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citizen', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='job',
            name='place_of_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='organizations.company', verbose_name='Место работы'),
        ),
    ]
