# Generated by Django 3.2.8 on 2023-03-30 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('citizens', '0002_auto_20230330_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='disability_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='citizens.disabilitytype', verbose_name='ОВЗ'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='citizens.school', verbose_name='Школа'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='citizens.schoolclass', verbose_name='Школный класс'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='citizen', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
