# Generated by Django 3.2.5 on 2021-08-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0002_citizen_copp_registration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citizen',
            options={'verbose_name': 'Гражданин', 'verbose_name_plural': 'Граждане'},
        ),
        migrations.AlterField(
            model_name='citizen',
            name='education_type',
            field=models.CharField(blank=True, choices=[('SPO', 'СПО'), ('VO', 'ВО'), ('SSPO', 'Cтудент ВО'), ('SVO', 'Cтудент СПО'), ('11', '11 классов'), ('9', '9 классов'), ('OTHR', 'Другой')], max_length=4, null=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='social_status',
            field=models.CharField(blank=True, choices=[('SCHS', 'Обучающиеся общеообразовательных организаций'), ('SSPO', 'студент СПО'), ('SVO', 'студент ВО'), ('EMP', 'Cотрудник предприятия'), ('SC', 'Гражданин предпенсионного возраста'), ('50+', 'Гражданин старше 50-ти лет'), ('UEMP', 'Безработный гражданин (статус ЦЗН)'), ('EMPS', 'Гражданин, ищущий работу (статус ЦЗН)'), ('OTHR', 'Другой')], max_length=4, null=True, verbose_name='Социальный статус'),
        ),
    ]
