# Generated by Django 3.2.8 on 2023-05-30 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0003_auto_20230330_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Муниципалитет',
                'verbose_name_plural': 'Муниципалитеты',
            },
        ),
        migrations.AlterField(
            model_name='school',
            name='inn',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='school',
            name='territorial_administration',
            field=models.CharField(blank=True, choices=[('TADM', 'Тольяттинское управление'), ('NWADM', 'Северо-Западное управление'), ('WADM', 'Западное управление'), ('SWADM', 'Юго-Западное управление'), ('POVADM', 'Поволжское управление'), ('SADM', 'Южное управление'), ('DEPSAM', 'Департамент образования г.о. Самара'), ('SEADM', 'Юго-Восточное управление'), ('OTRADM', 'Отрадненское управление'), ('CENTADM', 'Центральное управление'), ('NEADM', 'Северо-Восточное управление'), ('DEPTOL', 'Департамент образования г.о. Тольятти'), ('NADM', 'Северное управление'), ('KINADM', 'Кинельское управление'), ('SAMADM', 'Самарское управление')], max_length=20, null=True, verbose_name='Тер. управление'),
        ),
        migrations.AddField(
            model_name='school',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='citizens.municipality', verbose_name='Муниципалитет'),
        ),
    ]
