# Generated by Django 3.2.8 on 2023-06-16 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0004_auto_20230530_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolclass',
            name='school',
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='ed_center_group',
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='school_class',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='SchoolClass',
        ),
    ]
