# Generated by Django 3.2.5 on 2021-08-24 08:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0005_auto_20210824_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название школы')),
                ('specialty', models.CharField(blank=True, max_length=50, null=True, verbose_name='Уклон школы')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('adress', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школы',
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(11), django.core.validators.MinValueValidator(1)], verbose_name='Номер класса')),
                ('grade_letter', models.CharField(max_length=4, verbose_name='Буква класса')),
                ('specialty', models.CharField(blank=True, max_length=50, null=True, verbose_name='Уклон класса')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='citizens.school', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.AlterField(
            model_name='citizen',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='citizens.school', verbose_name='Школа'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='citizens.schoolclass', verbose_name='Школный класс'),
        ),
    ]
