# Generated by Django 3.2.8 on 2023-06-26 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0005_auto_20230616_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='aplication_stages',
        ),
    ]
