# Generated by Django 3.2.5 on 2021-08-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0006_auto_20210824_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
