# Generated by Django 3.2.5 on 2021-09-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0007_citizen_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='disability_type',
            field=models.CharField(blank=True, choices=[('SPO', 'СПО'), ('VO', 'ВО'), ('SSPO', 'Cтудент ВО'), ('SVO', 'Cтудент СПО'), ('11', '11 классов'), ('9', '9 классов'), ('OTHR', 'Другой')], default=None, max_length=4, null=True, verbose_name='Инвалидность'),
        ),
    ]
