# Generated by Django 3.2.5 on 2021-09-07 09:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('citizens', '0008_citizen_disability_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_coordinators',
            field=models.ManyToManyField(related_name='coordinated_schools', to=settings.AUTH_USER_MODEL, verbose_name='Координаторы'),
        ),
    ]
