# Generated by Django 3.2.5 on 2021-09-14 09:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('citizens', '0009_school_school_coordinators'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_bilet',
            field=models.BooleanField(default=False, verbose_name='Есть педагог-навигатор'),
        ),
        migrations.AddField(
            model_name='school',
            name='municipality',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Муниципалитет'),
        ),
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Населённый пункт'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_coordinators',
            field=models.ManyToManyField(blank=True, related_name='coordinated_schools', to=settings.AUTH_USER_MODEL, verbose_name='Координаторы'),
        ),
    ]
