# Generated by Django 3.2.8 on 2021-10-22 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education_centers', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('citizens', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocGuidTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Название пробы')),
                ('education_program_link', models.URLField(verbose_name='Программа обучения (ссылка)')),
                ('age_group', models.CharField(blank=True, choices=[('6-7', '6-7 класс'), ('8-9', '8-9 класс'), ('10-11', '10-11 класс'), ('ALL', 'Единая')], max_length=5, null=True, verbose_name='Возрастная группа')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Описание')),
                ('img_link', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Ссылка на изображение')),
                ('attendance_limit', models.IntegerField(default=8, verbose_name='Максимальное кол-во участников')),
                ('guid_type', models.CharField(choices=[('SPO', 'На площадке исторический парк «Россия – Моя история»'), ('VO', 'В онлайн формате'), ('EC', 'На базе ЦО')], default='VO', max_length=4, verbose_name='Тип проб')),
                ('education_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voc_guid_sessions', to='education_centers.educationcenter', verbose_name='Центр обучения')),
                ('participants', models.ManyToManyField(blank=True, related_name='voc_guid_tests', to='citizens.Citizen', verbose_name='Участники')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education_centers.workshop', verbose_name='Место проведения')),
            ],
            options={
                'verbose_name': 'Проф. проба',
                'verbose_name_plural': 'Проф. пробы',
            },
        ),
        migrations.CreateModel(
            name='VocGuidGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(blank=True, choices=[('6-7', '6-7 класс'), ('8-9', '8-9 класс'), ('10-11', '10-11 класс')], max_length=5, null=True, verbose_name='Возрастная группа')),
                ('attendance_limit', models.IntegerField(default=8, verbose_name='Максимальное кол-во участников')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Населённый пункт')),
                ('bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='vocational_guidance.vocguidtest', verbose_name='Бандл')),
                ('participants', models.ManyToManyField(related_name='voc_guid_groups', to='citizens.Citizen', verbose_name='Участники')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guid_groups', to='citizens.school', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Группа по проф. ориентации',
                'verbose_name_plural': 'Группы по проф. ориентации',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('slot', models.CharField(choices=[('MRN', 'с 10:00 до 11:30'), ('MID', 'с 15:00 до 16:30'), ('EVN', 'с 16:30 до 18:00')], max_length=5, verbose_name='Временной промежуток')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vocational_guidance.vocguidgroup', verbose_name='Группы')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vocational_guidance.vocguidtest', verbose_name='Пробы')),
            ],
            options={
                'verbose_name': 'Слот',
                'verbose_name_plural': 'Слоты',
            },
        ),
        migrations.CreateModel(
            name='EducatorNavigator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ed_navs', to='citizens.school', verbose_name='Школа')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Педагог-навигатор',
                'verbose_name_plural': 'Педагоги-навигаторы',
            },
        ),
    ]
