# Generated by Django 4.0.6 on 2022-08-29 10:05

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education_centers', '0002_initial'),
        ('citizens', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200, verbose_name='Улица')),
                ('building_number', models.CharField(max_length=10, verbose_name='Дом')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('apartment', models.CharField(blank=True, max_length=10, null=True, verbose_name='Аудитория')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Населённый пункт',
                'verbose_name_plural': 'Населённые пункты',
            },
        ),
        migrations.CreateModel(
            name='VocGuidTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500, verbose_name='Название пробы')),
                ('short_description', models.CharField(max_length=130, verbose_name='Краткое описание')),
                ('description', models.TextField(verbose_name='Описание')),
                ('attendance_limit', models.IntegerField(default=8, verbose_name='Лимит участников')),
                ('participants_count', models.IntegerField(default=0, verbose_name='Колво участников')),
                ('start_datetime', models.DateTimeField(default=datetime.datetime(2022, 8, 29, 14, 5, 38, 766138), verbose_name='Дата и время начала')),
                ('is_online', models.BooleanField(default=True, verbose_name='Онлайн')),
                ('conference_data', models.CharField(blank=True, max_length=350, null=True, verbose_name='данные для подключения')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vocational_guidance.address', verbose_name='Адресс')),
                ('competence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voc_guids', to='education_centers.competence', verbose_name='Компетенция')),
                ('education_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voc_guid_sessions', to='education_centers.educationcenter', verbose_name='Центр обучения')),
                ('participants', models.ManyToManyField(blank=True, related_name='voc_guid_tests', to='citizens.citizen', verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Проф. проба',
                'verbose_name_plural': 'Проф. пробы',
            },
        ),
        migrations.CreateModel(
            name='TestContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='ФИО преподователя')),
                ('email', models.EmailField(blank=True, max_length=300, null=True, verbose_name='Email преподователя')),
                ('phone', models.CharField(blank=True, max_length=300, null=True, verbose_name='Телефон преподователя')),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='vocational_guidance.vocguidtest', verbose_name='Проф. проба')),
            ],
            options={
                'verbose_name': 'Контакты преподавателя',
                'verbose_name_plural': 'Контакты преподователей',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_attend', models.BooleanField(default=False, verbose_name='Посетил')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='citizens.citizen', verbose_name='Ученик')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='vocational_guidance.vocguidtest', verbose_name='Проба')),
            ],
            options={
                'verbose_name': 'Посещаемость',
                'verbose_name_plural': 'Посещаемость',
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Оценка')),
                ('criterion', models.CharField(max_length=70, null=True, verbose_name='Название критерия')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='citizens.citizen', verbose_name='Ученик')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='vocational_guidance.vocguidtest', verbose_name='Проба')),
            ],
            options={
                'verbose_name': 'Ассессмент',
                'verbose_name_plural': 'Ассессмент',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='vocational_guidance.city', verbose_name='Населённый пункт'),
        ),
    ]
