# Generated by Django 3.2.5 on 2021-08-24 09:40

import citizens.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education_centers', '0015_auto_20210824_1249'),
        ('citizens', '0006_auto_20210824_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocGuidGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(choices=[('6-7', '6-7 класс'), ('8-9', '8-9 класс'), ('10-11', '10-11 класс')], max_length=5, verbose_name='Возрастная группа')),
                ('participants', models.ManyToManyField(limit_choices_to={citizens.models.SchoolClass: True}, related_name='voc_guid_group', to='citizens.Citizen', verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Группа по проф. ориентации',
                'verbose_name_plural': 'Группы по проф. ориентации',
            },
        ),
        migrations.CreateModel(
            name='VocGuidBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programs_count', models.IntegerField(verbose_name='Количество проб')),
                ('programs', models.ManyToManyField(to='education_centers.EducationProgram', verbose_name='Список проб')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время завершения')),
                ('bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vocational_guidance.vocguidbundle', verbose_name='Пробы')),
                ('education_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='education_centers.educationcenter', verbose_name='Организатор проб')),
                ('groups', models.ManyToManyField(to='vocational_guidance.VocGuidGroup', verbose_name='Группы')),
            ],
            options={
                'verbose_name': 'Слот',
                'verbose_name_plural': 'Слоты',
            },
        ),
    ]
