# Generated by Django 3.2.8 on 2021-10-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0002_auto_20211023_1739'),
        ('vocational_guidance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocguidtest',
            name='disability_type',
            field=models.ManyToManyField(to='citizens.DisabilityType', verbose_name='ОВЗ'),
        ),
        migrations.DeleteModel(
            name='EducatorNavigator',
        ),
    ]
