# Generated by Django 3.2.5 on 2021-08-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocational_guidance', '0002_auto_20210824_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocguidbundle',
            name='programs_count',
        ),
        migrations.AddField(
            model_name='vocguidbundle',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='vocguidbundle',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Название пакета'),
        ),
    ]
