# Generated by Django 3.2.8 on 2021-10-23 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocational_guidance', '0002_auto_20211023_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocguidtest',
            old_name='disability_type',
            new_name='disability_types',
        ),
    ]
