# Generated by Django 3.2.5 on 2021-08-31 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0007_citizen_birthday'),
        ('vocational_guidance', '0005_auto_20210830_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocguidbundle',
            name='img_link',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='vocguidbundle',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='voc_guid_bundles', to='citizens.Citizen', verbose_name='Участники'),
        ),
    ]
