# Generated by Django 3.2.8 on 2021-10-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocational_guidance', '0006_auto_20211024_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocguidtest',
            name='zoom_link',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='zoom_link',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Ссылка на конференцию (zoom)'),
        ),
        migrations.AddField(
            model_name='vocguidtest',
            name='education_program_link',
            field=models.URLField(blank=True, null=True, verbose_name='Программа обучения (ссылка)'),
        ),
    ]
