# Generated by Django 3.2.5 on 2021-08-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0015_auto_20210824_1249'),
        ('vocational_guidance', '0006_auto_20210831_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocguidbundle',
            name='programs',
            field=models.ManyToManyField(blank=True, null=True, to='education_centers.EducationProgram', verbose_name='Список проб'),
        ),
    ]
