# Generated by Django 3.2.8 on 2021-10-24 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocational_guidance', '0007_auto_20211024_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='vocational_guidance.vocguidgroup', verbose_name='Группы'),
        ),
    ]
