# Generated by Django 3.2.5 on 2021-09-02 09:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0015_auto_20210824_1249'),
        ('vocational_guidance', '0007_alter_vocguidbundle_programs'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocGuidSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('Rus', 'На площадке исторический парк «Россия – Моя история»'), ('On', 'В онлайн формате'), ('Off', 'На базе ЦО')], max_length=3, verbose_name='Тип пробы')),
                ('attendance_limit', models.IntegerField(verbose_name='Лимит участников')),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=3600), verbose_name='Длительность')),
                ('education_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voc_guid_sessions', to='education_centers.educationcenter', verbose_name='Центр обучения')),
                ('education_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voc_guid_sessions', to='education_centers.educationprogram', verbose_name='Программа обучения')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voc_guid_sessions', to='education_centers.workshop', verbose_name='Место проведения')),
            ],
            options={
                'verbose_name': 'Группа по проф. ориентации',
                'verbose_name_plural': 'Группы по проф. ориентации',
            },
        ),
    ]
