# Generated by Django 3.2.5 on 2021-09-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0008_citizen_disability_type'),
        ('vocational_guidance', '0008_vocguidsession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vocguidsession',
            options={'verbose_name': 'Проф. проба', 'verbose_name_plural': 'Проф. пробы'},
        ),
        migrations.RemoveField(
            model_name='vocguidbundle',
            name='education_center',
        ),
        migrations.RemoveField(
            model_name='vocguidbundle',
            name='programs',
        ),
        migrations.AddField(
            model_name='vocguidbundle',
            name='attendance_limit',
            field=models.IntegerField(default=50, verbose_name='Максимальное кол-во участников'),
        ),
        migrations.AddField(
            model_name='vocguidbundle',
            name='sessions',
            field=models.ManyToManyField(to='vocational_guidance.VocGuidSession', verbose_name='Список проб'),
        ),
        migrations.AddField(
            model_name='vocguidgroup',
            name='attendance_limit',
            field=models.IntegerField(default=50, verbose_name='Максимальное кол-во участников'),
        ),
        migrations.AlterField(
            model_name='vocguidbundle',
            name='guid_type',
            field=models.CharField(blank=True, choices=[('SPO', 'На площадке исторический парк «Россия – Моя история»'), ('VO', 'В онлайн формате'), ('EC', 'На базе ЦО')], max_length=4, null=True, verbose_name='Тип проб'),
        ),
        migrations.AlterField(
            model_name='vocguidbundle',
            name='participants',
            field=models.ManyToManyField(related_name='voc_guid_bundles', to='citizens.Citizen', verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='vocguidsession',
            name='attendance_limit',
            field=models.IntegerField(default=50, verbose_name='Лимит участников'),
        ),
    ]
