# Generated by Django 3.2.5 on 2021-09-04 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0008_citizen_disability_type'),
        ('vocational_guidance', '0009_auto_20210904_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocguidgroup',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guid_groups', to='citizens.school', verbose_name='Школа'),
        ),
        migrations.AlterField(
            model_name='vocguidgroup',
            name='age_group',
            field=models.CharField(blank=True, choices=[('6-7', '6-7 класс'), ('8-9', '8-9 класс'), ('10-11', '10-11 класс')], max_length=5, null=True, verbose_name='Возрастная группа'),
        ),
    ]
