# Generated by Django 3.2.5 on 2021-09-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0008_citizen_disability_type'),
        ('vocational_guidance', '0010_auto_20210904_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocguidgroup',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='voc_guid_groups', to='citizens.Citizen', verbose_name='Участники'),
        ),
    ]
