# Generated by Django 3.2.5 on 2021-09-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0009_school_school_coordinators'),
        ('vocational_guidance', '0011_alter_vocguidgroup_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocguidgroup',
            name='participants',
            field=models.ManyToManyField(related_name='voc_guid_groups', to='citizens.Citizen', verbose_name='Участники'),
        ),
    ]
