# Generated by Django 3.2.5 on 2021-09-07 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocational_guidance', '0012_alter_vocguidgroup_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocguidgroup',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='vocational_guidance.vocguidbundle', verbose_name='Бандл'),
        ),
    ]
