# Generated by Django 3.2.5 on 2021-09-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocational_guidance', '0013_vocguidgroup_bundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocguidgroup',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Населённый пункт'),
        ),
    ]
