# Generated by Django 3.2.8 on 2021-10-19 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210908_1038'),
        ('citizens', '0011_auto_20210914_1411'),
        ('vocational_guidance', '0014_vocguidgroup_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educator_navigator',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ed_navs', to='citizens.school', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Педагог-навигатор',
                'verbose_name_plural': 'Педагоги-навигаторы',
            },
            bases=('users.user',),
        ),
    ]
