# Generated by Django 3.2.8 on 2021-10-19 09:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0011_auto_20210914_1411'),
        ('field_history', '0003_alter_fieldhistory_id'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('education_centers', '0018_alter_educationcenter_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('federal_empl_program', '0019_alter_application_category'),
        ('vocational_guidance', '0015_educator_navigator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Educator_navigator',
            new_name='EducatorNavigator',
        ),
    ]
