# Generated by Django 3.2.8 on 2021-10-19 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0018_alter_educationcenter_name'),
        ('vocational_guidance', '0016_rename_educator_navigator_educatornavigator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocguidsession',
            name='education_center',
        ),
        migrations.CreateModel(
            name='VocGuidTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Название пробы')),
                ('education_program_link', models.URLField(verbose_name='Программа обучения')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Описание')),
                ('img_link', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Ссылка на изображение')),
                ('attendance_limit', models.IntegerField(default=8, verbose_name='Максимальное кол-во участников')),
                ('guid_type', models.CharField(choices=[('SPO', 'На площадке исторический парк «Россия – Моя история»'), ('VO', 'В онлайн формате'), ('EC', 'На базе ЦО')], default='VO', max_length=4, verbose_name='Тип проб')),
                ('education_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voc_guid_sessions', to='education_centers.educationcenter', verbose_name='Центр обучения')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education_centers.workshop', verbose_name='Место проведения')),
            ],
            options={
                'verbose_name': 'Проф. проба',
                'verbose_name_plural': 'Проф. пробы',
            },
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vocational_guidance.vocguidtest', verbose_name='Пробы'),
        ),
        migrations.AlterField(
            model_name='vocguidgroup',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='vocational_guidance.vocguidtest', verbose_name='Бандл'),
        ),
        migrations.DeleteModel(
            name='VocGuidBundle',
        ),
    ]
