# Generated by Django 3.2.8 on 2021-10-19 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocational_guidance', '0017_auto_20211019_1333'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VocGuidSession',
        ),
    ]
