# Generated by Django 3.2.8 on 2021-10-19 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0011_auto_20210914_1411'),
        ('education_centers', '0018_alter_educationcenter_name'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('federal_empl_program', '0019_alter_application_category'),
        ('field_history', '0003_alter_fieldhistory_id'),
        ('vocational_guidance', '0018_delete_vocguidsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='bundle',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='education_center',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='vocguidgroup',
            name='bundle',
        ),
        migrations.RemoveField(
            model_name='vocguidgroup',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='vocguidgroup',
            name='school',
        ),
        migrations.RemoveField(
            model_name='vocguidtest',
            name='education_center',
        ),
        migrations.RemoveField(
            model_name='vocguidtest',
            name='workshop',
        ),
        migrations.DeleteModel(
            name='EducatorNavigator',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
        migrations.DeleteModel(
            name='VocGuidGroup',
        ),
        migrations.DeleteModel(
            name='VocGuidTest',
        ),
    ]
