# Generated by Django 3.2.8 on 2021-10-19 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20210908_1038'),
        ('citizens', '0011_auto_20210914_1411'),
        ('education_centers', '0018_alter_educationcenter_name'),
        ('vocational_guidance', '0019_auto_20211019_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocGuidTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Название пробы')),
                ('education_program_link', models.URLField(verbose_name='Программа обучения')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Описание')),
                ('img_link', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Ссылка на изображение')),
                ('attendance_limit', models.IntegerField(default=8, verbose_name='Максимальное кол-во участников')),
                ('guid_type', models.CharField(choices=[('SPO', 'На площадке исторический парк «Россия – Моя история»'), ('VO', 'В онлайн формате'), ('EC', 'На базе ЦО')], default='VO', max_length=4, verbose_name='Тип проб')),
                ('education_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voc_guid_sessions', to='education_centers.educationcenter', verbose_name='Центр обучения')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education_centers.workshop', verbose_name='Место проведения')),
            ],
            options={
                'verbose_name': 'Проф. проба',
                'verbose_name_plural': 'Проф. пробы',
            },
        ),
        migrations.CreateModel(
            name='VocGuidGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(blank=True, choices=[('6-7', '6-7 класс'), ('8-9', '8-9 класс'), ('10-11', '10-11 класс')], max_length=5, null=True, verbose_name='Возрастная группа')),
                ('attendance_limit', models.IntegerField(default=50, verbose_name='Максимальное кол-во участников')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Населённый пункт')),
                ('bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='vocational_guidance.vocguidtest', verbose_name='Бандл')),
                ('participants', models.ManyToManyField(related_name='voc_guid_groups', to='citizens.Citizen', verbose_name='Участники')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guid_groups', to='citizens.school', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Группа по проф. ориентации',
                'verbose_name_plural': 'Группы по проф. ориентации',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время завершения')),
                ('bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vocational_guidance.vocguidtest', verbose_name='Пробы')),
                ('education_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='education_centers.educationcenter', verbose_name='Организатор проб')),
                ('groups', models.ManyToManyField(to='vocational_guidance.VocGuidGroup', verbose_name='Группы')),
            ],
            options={
                'verbose_name': 'Слот',
                'verbose_name_plural': 'Слоты',
            },
        ),
        migrations.CreateModel(
            name='EducatorNavigator',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ed_navs', to='citizens.school', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Педагог-навигатор',
                'verbose_name_plural': 'Педагоги-навигаторы',
            },
            bases=('users.user',),
        ),
    ]
