# Generated by Django 3.2.5 on 2021-07-29 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название компетенции')),
                ('block', models.CharField(blank=True, choices=[('IT', 'Информационные и коммуникационные технологии'), ('SR', 'Сфера услуг'), ('BD', 'Строительство и строительные технологии'), ('MF', 'Производство и инженерные технологии'), ('DS', 'Творчество и дизайн'), ('TR', 'Транспорт и логистика'), ('ED', 'Образование')], max_length=2, null=True, verbose_name='Блок')),
                ('competence_stage', models.CharField(blank=True, choices=[('MN', 'Основная'), ('PR', 'Презентационная')], max_length=2, null=True, verbose_name='Стадия')),
                ('competence_type', models.CharField(blank=True, choices=[('RU', 'WorldSkills Russia'), ('WSI', 'WorldSkills International'), ('WSE', 'WorldSkills Eurasia')], max_length=3, null=True, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Компетенция',
                'verbose_name_plural': 'Компетенции',
            },
        ),
        migrations.CreateModel(
            name='EducationCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название организации')),
                ('competences', models.ManyToManyField(blank=True, related_name='educationCenters', to='education_centers.Competence', verbose_name='Компетенции')),
                ('contact_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='education_centers', to=settings.AUTH_USER_MODEL, verbose_name='Контактное лицо')),
            ],
            options={
                'verbose_name': 'Центр обучения',
                'verbose_name_plural': 'Центры обучения',
            },
        ),
        migrations.CreateModel(
            name='EducationProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=150, verbose_name='Название программы')),
                ('program_type', models.CharField(blank=True, choices=[('DPOPK', 'ДПО ПК'), ('DPOPP', 'ДПО ПП'), ('POP', 'ПО П'), ('POPP', 'ПО ПП'), ('POPK', 'ПО ПК')], max_length=5, null=True, verbose_name='Тип программы')),
                ('duration', models.IntegerField(blank=True, choices=[(72, '72 ч.'), (144, '144 ч.'), (256, '256 ч.')], verbose_name='Длительность (ак. часов)')),
                ('program_link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на программу')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='education_centers.competence', verbose_name='Компетенция')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программы',
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=200, verbose_name='Адрес')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='education_centers.competence', verbose_name='Компетенция')),
                ('education_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='education_centers.educationcenter', verbose_name='Центр обучения')),
            ],
            options={
                'verbose_name': 'Мастерская',
                'verbose_name_plural': 'Мастерские',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Номер группы')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала обучения')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания обучения')),
                ('distance_education', models.BooleanField(default=False, verbose_name='Дистанционное обучение')),
                ('mixed_education', models.BooleanField(default=False, verbose_name='Смешанное обучение')),
                ('education_project', models.CharField(blank=True, choices=[('COMM', 'Комерция'), ('PoE', 'Содействие занятости'), ('OTHR', 'Другое')], max_length=4, null=True, verbose_name='Федеральная программа')),
                ('education_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='education_centers.educationprogram', verbose_name='Программа обучения')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='groups', to='education_centers.workshop', verbose_name='мастерская')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
    ]
