# Generated by Django 3.2.8 on 2021-10-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название компетенции'),
        ),
    ]
