# Generated by Django 3.2.8 on 2023-08-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0001_squashed_0049_auto_20230616_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='bank',
            field=models.CharField(max_length=250, verbose_name='Банк'),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='inn',
            field=models.CharField(max_length=25, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='kpp',
            field=models.CharField(max_length=25, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='legal_address',
            field=models.CharField(max_length=500, verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='mail_address',
            field=models.CharField(max_length=500, verbose_name='Почтовый адрес'),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='okpo',
            field=models.CharField(max_length=25, verbose_name='ОКПО'),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='oktmo',
            field=models.CharField(max_length=25, verbose_name='ОКТМО'),
        ),
        migrations.AlterField(
            model_name='contractorsdocument',
            name='register_number',
            field=models.IntegerField(verbose_name='Номер в реестре'),
        ),
    ]
