# Generated by Django 3.2.5 on 2021-08-14 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='for_inline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inline_test_models', to='education_centers.competence'),
        ),
        migrations.AddField(
            model_name='competence',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_test_models', to='education_centers.competence'),
        ),
    ]
