# Generated by Django 3.2.8 on 2023-03-30 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education_centers', '0002_alter_educationcentergroup_education_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationcenter',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education_centers', to=settings.AUTH_USER_MODEL, verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='group',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='education_centers.workshop', verbose_name='мастерская'),
        ),
    ]
