# Generated by Django 3.2.5 on 2021-08-14 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0002_auto_20210815_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competence',
            name='for_inline',
        ),
        migrations.RemoveField(
            model_name='competence',
            name='test',
        ),
        migrations.CreateModel(
            name='TModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('for_inline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inline_test_models', to='education_centers.tmodel')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_test_models', to='education_centers.tmodel')),
            ],
        ),
    ]
