# Generated by Django 3.2.8 on 2021-10-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0002_alter_competence_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationcenter',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Название организации'),
        ),
    ]
