# Generated by Django 3.2.8 on 2023-10-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0003_auto_20231005_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationcenter',
            name='flow_name',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Название на flow'),
        ),
    ]
