# Generated by Django 3.2.8 on 2021-10-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0003_alter_educationcenter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationprogram',
            name='program_name',
            field=models.CharField(max_length=300, verbose_name='Название программы'),
        ),
    ]
