# Generated by Django 3.2.5 on 2021-08-14 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0003_auto_20210815_0052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TModel',
        ),
    ]
