# Generated by Django 3.2.5 on 2021-08-16 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0004_delete_tmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationCenterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_group_size', models.IntegerField(verbose_name='Минимальный размер группы')),
                ('max_group_size', models.IntegerField(verbose_name='Максимальный размер группы')),
                ('study_periods', models.CharField(blank=True, choices=[('MRNG', '09.00-13.00'), ('DAYT', '13.00-17.00'), ('EVNG', '17.00-21.00')], max_length=4, null=True, verbose_name='Период проведения занятий')),
                ('start_date', models.DateField(verbose_name='Дата старта')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окночания')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ed_center_groups', to='education_centers.competence', verbose_name='Компетенция')),
                ('education_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ed_center_groups', to='education_centers.educationcenter', verbose_name='Центр обучения')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ed_center_group', to='education_centers.group', verbose_name='Группа Express')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ed_center_groups', to='education_centers.educationprogram', verbose_name='Программа подготовки')),
            ],
            options={
                'verbose_name': 'ЦО группа',
                'verbose_name_plural': 'ЦО группы',
            },
        ),
    ]
