# Generated by Django 3.2.8 on 2023-03-31 08:58

from django.db import migrations, models
import django.db.models.deletion
import education_centers.models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0004_alter_educationcenter_contact_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorsDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('GRMNT', 'Договор и приложения'), ('SSGMNT', 'Задание на оказание услуг'), ('NVC', 'Счёт на оплату'), ('CT', 'Акт выполненных работ')], max_length=6, verbose_name='Тип документа')),
                ('doc_file', models.FileField(upload_to=education_centers.models.ContractorsDocument.doc_directory_path, verbose_name='Документ')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ed_center_documents', to='education_centers.educationcenter', verbose_name='подрядчик')),
            ],
            options={
                'verbose_name': 'Документ с подрядчиком',
                'verbose_name_plural': 'Документы с подрядчиками',
            },
        ),
    ]
