# Generated by Django 4.2 on 2023-11-27 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
        ('education_centers', '0004_educationcenter_flow_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbilimpicsWinner',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_send', models.BooleanField(default=False, verbose_name='Сертификат отправлен')),
                ('is_received', models.BooleanField(default=False, verbose_name='Сертификат получен')),
                ('competence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='abilimpics_winners', to='education_centers.competence', verbose_name='Компетенция')),
                ('ed_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='abilimpics_winners', to='education_centers.educationcenter', verbose_name='Центр обучения')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='abilimpics_winners', to='education_centers.educationprogram', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.user',),
        ),
    ]
