# Generated by Django 3.2.8 on 2023-03-31 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0005_contractorsdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorsdocument',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_documents', to='education_centers.group', verbose_name='группа'),
            preserve_default=False,
        ),
    ]
