# Generated by Django 3.2.5 on 2021-08-16 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0005_educationcentergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationcentergroup',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ed_center_group', to='education_centers.group', verbose_name='Группа Express'),
        ),
        migrations.AlterField(
            model_name='educationcentergroup',
            name='max_group_size',
            field=models.IntegerField(verbose_name='Максимальный размер'),
        ),
        migrations.AlterField(
            model_name='educationcentergroup',
            name='min_group_size',
            field=models.IntegerField(verbose_name='Минимальный размер'),
        ),
    ]
