# Generated by Django 4.2 on 2023-11-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0006_alter_abilimpicswinner_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationprogram',
            name='is_abilimpics',
            field=models.BooleanField(default=False, verbose_name='Абилимпикс?'),
        ),
    ]
