# Generated by Django 3.2.5 on 2021-08-16 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0006_auto_20210816_1557'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EducationCenterGroup',
        ),
    ]
