# Generated by Django 3.2.8 on 2023-04-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0006_contractorsdocument_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractorsdocument',
            name='group',
        ),
        migrations.AddField(
            model_name='contractorsdocument',
            name='groups',
            field=models.ManyToManyField(related_name='group_documents', to='education_centers.Group', verbose_name='группы'),
        ),
    ]
