# Generated by Django 4.2 on 2023-11-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0007_educationprogram_is_abilimpics'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationprogram',
            name='period',
            field=models.IntegerField(blank=True, null=True, verbose_name='Период обучения'),
        ),
    ]
