# Generated by Django 3.2.8 on 2023-04-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0007_auto_20230403_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorsdocument',
            name='doc_stage',
            field=models.CharField(choices=[('CRTD', 'Создан'), ('CHCKD', 'Проверен'), ('SGND', 'Подписан')], default='CRTD', max_length=6, verbose_name='Стадия'),
        ),
    ]
