# Generated by Django 3.2.5 on 2021-08-16 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0008_educationcentergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationcentergroup',
            name='ed_schedule_link',
            field=models.URLField(blank=True, max_length=256, null=True, verbose_name='Ссылка на график обучения'),
        ),
        migrations.AlterField(
            model_name='educationcentergroup',
            name='study_days_count',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)], verbose_name='Занятий в неделю'),
        ),
    ]
