# Generated by Django 3.2.8 on 2023-04-03 12:15

from django.db import migrations, models
import education_centers.models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0008_contractorsdocument_doc_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Тип документа')),
                ('stage', models.CharField(choices=[('GRMNT', 'Договорные'), ('CLS', 'Закрывающие'), ('PRV', 'Подтверждающие')], max_length=6, verbose_name='Этап')),
                ('template', models.FileField(upload_to=education_centers.models.DocumentType.template_directory_path, verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Шаблон документов',
                'verbose_name_plural': 'Шаблоны документов',
            },
        ),
        migrations.RemoveField(
            model_name='contractorsdocument',
            name='doc_type',
        ),
    ]
