# Generated by Django 4.2 on 2023-11-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0008_educationprogram_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationprogram',
            name='period',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Период обучения'),
        ),
    ]
