# Generated by Django 3.2.5 on 2021-08-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0009_auto_20210816_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationcentergroup',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Показывать в списке планируемого обучения'),
        ),
        migrations.AlterField(
            model_name='educationcentergroup',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
    ]
