# Generated by Django 3.2.8 on 2023-04-03 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0009_auto_20230403_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorsdocument',
            name='doc_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='education_centers.documenttype', verbose_name='Тип документа'),
        ),
    ]
