# Generated by Django 4.2 on 2023-12-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0009_alter_educationprogram_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='pay_status',
            field=models.CharField(choices=[('WFB', 'Ожидаем счета'), ('UPB', 'Счета подгруженны частично'), ('PDB', 'Счета оплаченны частично'), ('UPBF', 'Все счета подгруженны'), ('PDBF', 'Счета оплаченны полностью')], default='WFB', max_length=4, verbose_name='Статус оплаты'),
        ),
    ]
