# Generated by Django 4.2 on 2023-12-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0010_group_pay_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='pay_status',
            field=models.CharField(choices=[('WFB', 'Проверка'), ('UPB', 'На оплату'), ('PDB', 'Оплачен')], default='WFB', max_length=4, verbose_name='Статус оплаты'),
        ),
    ]
