# Generated by Django 3.2.8 on 2023-04-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0010_contractorsdocument_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationcenter',
            name='ed_license',
            field=models.TextField(blank=True, null=True, verbose_name='Образовательная лизенция'),
        ),
        migrations.AddField(
            model_name='educationcenter',
            name='legal_address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес места нахождения'),
        ),
        migrations.AddField(
            model_name='educationcenter',
            name='org_document',
            field=models.TextField(blank=True, null=True, verbose_name='Действует на основаннии:'),
        ),
    ]
