# Generated by Django 4.2.6 on 2023-12-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0011_alter_group_pay_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Цифровой след'),
        ),
    ]
