# Generated by Django 3.2.8 on 2023-04-04 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0011_auto_20230404_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationCenterHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('position', models.CharField(max_length=50, verbose_name='Должность')),
                ('first_name_r', models.CharField(max_length=30, verbose_name='Имя (род)')),
                ('middle_name_r', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество (род)')),
                ('last_name_r', models.CharField(max_length=30, verbose_name='Фамилия (род)')),
                ('position_r', models.CharField(max_length=50, verbose_name='Должность (род)')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='head', to='education_centers.educationcenter', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Представитель организации',
                'verbose_name_plural': 'Представители организаций',
            },
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn_kpp', models.CharField(max_length=25, verbose_name='ИНН/КПП')),
                ('ogrn', models.CharField(max_length=25, verbose_name='ОГРН')),
                ('receiver', models.TextField(verbose_name='Получатель')),
                ('account_number', models.CharField(max_length=25, verbose_name='Расчётный счёт')),
                ('biс', models.CharField(max_length=25, verbose_name='БИК')),
                ('corr_account', models.CharField(max_length=25, verbose_name='К/сч')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='education_centers.educationcenter', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Реквизиты организации',
                'verbose_name_plural': 'Реквизиты организаций',
            },
        ),
    ]
