# Generated by Django 3.2.5 on 2021-08-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0003_auto_20210820_1041'),
        ('education_centers', '0012_auto_20210824_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='students',
            field=models.ManyToManyField(related_name='school', to='citizens.Citizen', verbose_name='Школьники'),
        ),
        migrations.DeleteModel(
            name='SchoolStudent',
        ),
    ]
