# Generated by Django 3.2.8 on 2023-04-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0012_bankdetails_educationcenterhead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetails',
            name='inn_kpp',
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='inn',
            field=models.CharField(default=123, max_length=25, verbose_name='ИНН'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='kpp',
            field=models.CharField(default=123, max_length=25, verbose_name='КПП'),
            preserve_default=False,
        ),
    ]
