# Generated by Django 4.2.6 on 2023-12-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0012_group_group_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_commentary',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Комментарий'),
        ),
    ]
