# Generated by Django 3.2.8 on 2023-04-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0013_auto_20230404_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationcenter',
            name='ed_license',
            field=models.BooleanField(default=False, verbose_name='Образовательная лизенция'),
        ),
    ]
