# Generated by Django 3.2.5 on 2021-08-24 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0013_auto_20210824_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolclass',
            name='students',
        ),
    ]
