# Generated by Django 4.2.6 on 2023-12-23 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0018_contract'),
        ('education_centers', '0013_group_group_commentary'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='groups', to='federal_empl_program.contract', verbose_name='Договор'),
        ),
    ]
