# Generated by Django 3.2.8 on 2023-04-06 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0014_alter_educationcenter_ed_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorsdocument',
            name='parent_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education_centers.contractorsdocument', verbose_name='Родительский документ'),
        ),
        migrations.AddField(
            model_name='contractorsdocument',
            name='register_number',
            field=models.IntegerField(default=1, verbose_name='Номер в реестре'),
            preserve_default=False,
        ),
    ]
