# Generated by Django 4.2.6 on 2023-12-23 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('federal_empl_program', '0019_employmentinvoice'),
        ('education_centers', '0014_group_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='employment_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='groups', to='federal_empl_program.employmentinvoice', verbose_name='Счёт (30%)'),
        ),
    ]
