# Generated by Django 3.2.8 on 2023-04-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0015_auto_20230406_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationcenter',
            name='is_license',
            field=models.BooleanField(default=False, verbose_name='Есть обр. лизенция?'),
        ),
        migrations.AlterField(
            model_name='educationcenter',
            name='ed_license',
            field=models.TextField(blank=True, null=True, verbose_name='Образовательная лизенция'),
        ),
    ]
