# Generated by Django 4.2.6 on 2023-12-24 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0015_group_employment_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='group',
            name='employment_invoice',
        ),
    ]
