# Generated by Django 3.2.5 on 2021-09-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0015_auto_20210824_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationcentergroup',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Город проведения'),
        ),
        migrations.AddField(
            model_name='educationcentergroup',
            name='is_online',
            field=models.BooleanField(blank=True, choices=[('on', 'Онлайн'), ('off', 'Очный')], default=False, max_length=4, null=True, verbose_name='Формат проведения'),
        ),
    ]
