# Generated by Django 3.2.5 on 2021-09-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0016_auto_20210906_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationcentergroup',
            name='is_online',
            field=models.CharField(choices=[('on', 'Онлайн'), ('off', 'Очный')], default='off', max_length=4, verbose_name='Формат проведения'),
        ),
    ]
