# Generated by Django 4.2.6 on 2024-02-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0016_remove_group_contract_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='adress',
        ),
        migrations.AddField(
            model_name='workshop',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес'),
        ),
    ]
