# Generated by Django 4.2.6 on 2024-02-12 16:34

from django.db import migrations, models
import education_centers.models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0017_remove_workshop_adress_workshop_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationprogram',
            name='program_file',
            field=models.FileField(blank=True, null=True, upload_to=education_centers.models.EducationProgram.doc_directory_path, verbose_name='Программа (документ)'),
        ),
    ]
