# Generated by Django 3.2.5 on 2021-09-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0017_alter_educationcentergroup_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationcenter',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название организации'),
        ),
    ]
