# Generated by Django 3.2.8 on 2023-04-11 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0017_alter_contractorsdocument_parent_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorsdocument',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания'),
        ),
    ]
