# Generated by Django 3.2.8 on 2023-04-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0018_contractorsdocument_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetails',
            name='receiver',
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='accountant',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Главный бухгалтер'),
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='bank',
            field=models.CharField(default='Банк', max_length=250, verbose_name='Банк'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='legal_address',
            field=models.CharField(default='445007, Самарская область, г. Тольятти , улица Победы, влд. 7', max_length=500, verbose_name='Юридический адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='mail_address',
            field=models.CharField(default='445007, Самарская область, г. Тольятти , улица Победы, влд. 7', max_length=500, verbose_name='Почтовый адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='okpo',
            field=models.CharField(default=43504248, max_length=25, verbose_name='ОКПО'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='oktmo',
            field=models.CharField(default=63.11, max_length=25, verbose_name='ОКТМО'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='okved',
            field=models.CharField(default=63.11, max_length=25, verbose_name='ОКВЭД'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='other',
            field=models.TextField(blank=True, null=True, verbose_name='Другие реквизиты'),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='phone',
            field=models.CharField(max_length=120, verbose_name='Телефон(-ы)'),
        ),
    ]
