# Generated by Django 4.2.6 on 2024-02-13 06:22

from django.db import migrations, models
import education_centers.models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0018_educationprogram_program_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='consent_file',
            field=models.FileField(blank=True, null=True, upload_to=education_centers.models.Teacher.doc_directory_path, verbose_name='Согласие'),
        ),
    ]
