# Generated by Django 3.2.8 on 2023-04-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0019_auto_20230412_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_status',
            field=models.CharField(choices=[('NEW', 'Группа создана'), ('SED', 'Начало обучение'), ('COMP', 'Завершила обучение'), ('NCOM', 'Группа отменена')], default='NEW', max_length=4, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='group',
            name='education_project',
            field=models.CharField(blank=True, choices=[('COMM', 'Коммерция'), ('PoE', 'Содействие занятости'), ('OTHR', 'Другое')], max_length=4, null=True, verbose_name='Федеральная программа'),
        ),
    ]
