# Generated by Django 4.2.6 on 2024-02-28 14:14

from django.db import migrations, models
import education_centers.models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0019_teacher_consent_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationprogram',
            name='employer_review',
            field=models.FileField(blank=True, null=True, upload_to=education_centers.models.EducationProgram.irpo_directory_path, verbose_name='Рецензии работодателя (pdf)'),
        ),
        migrations.AddField(
            model_name='educationprogram',
            name='program_pdf',
            field=models.FileField(blank=True, null=True, upload_to=education_centers.models.EducationProgram.irpo_directory_path, verbose_name='Программа, подписанная работодателем (pdf)'),
        ),
        migrations.AddField(
            model_name='educationprogram',
            name='program_word',
            field=models.FileField(blank=True, null=True, upload_to=education_centers.models.EducationProgram.irpo_directory_path, verbose_name='Программа по шаблону ИРПО (word)'),
        ),
        migrations.AddField(
            model_name='educationprogram',
            name='teacher_review',
            field=models.FileField(blank=True, null=True, upload_to=education_centers.models.EducationProgram.irpo_directory_path, verbose_name='Рецензии преподавателя (pdf)'),
        ),
    ]
