# Generated by Django 3.2.8 on 2023-05-03 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0020_auto_20230414_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationcenterhead',
            name='email',
            field=models.EmailField(default='123', max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationcenterhead',
            name='phone',
            field=models.CharField(default='123', max_length=120, verbose_name='Телефон(-ы)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationprogram',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание компетенции'),
        ),
        migrations.AddField(
            model_name='educationprogram',
            name='education_form',
            field=models.CharField(blank=True, choices=[('PRTLN', 'Очно-заочная с применением ДОТ'), ('FLLLN', 'Очная с применением ДОТ '), ('PRT', 'Очно-заочная'), ('FLL', 'Очная')], max_length=5, null=True, verbose_name='Форма обучения'),
        ),
        migrations.AddField(
            model_name='educationprogram',
            name='education_type',
            field=models.CharField(blank=True, choices=[('NDC', 'Без образования'), ('SPO', 'Cреднее профессиональное образование')], max_length=4, null=True, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='educationprogram',
            name='entry_requirements',
            field=models.TextField(blank=True, null=True, verbose_name='Входные требования'),
        ),
        migrations.AddField(
            model_name='educationprogram',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Примечания'),
        ),
        migrations.AddField(
            model_name='educationprogram',
            name='profession',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на программу'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='classes_type',
            field=models.CharField(blank=True, choices=[('T', 'Теоритические занятия'), ('P', 'Практические занятия'), ('TP', 'Практические и теоритические занятия')], max_length=4, null=True, verbose_name='Вид занятий'),
        ),
        migrations.AlterField(
            model_name='contractorsdocument',
            name='doc_stage',
            field=models.CharField(choices=[('CRTD', 'Создан'), ('CHCKD', 'Проверен'), ('SGND', 'Подписан'), ('SGNDAP', 'Подписан и проверен')], default='CRTD', max_length=6, verbose_name='Стадия'),
        ),
        migrations.AlterField(
            model_name='educationcenter',
            name='ed_license',
            field=models.TextField(blank=True, null=True, verbose_name='Образовательная лизенция (серия, номер, дата, срок действия)'),
        ),
        migrations.AlterField(
            model_name='educationprogram',
            name='duration',
            field=models.IntegerField(blank=True, verbose_name='Длительность (ак. часов)'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_status',
            field=models.CharField(choices=[('NEW', 'Создана'), ('SED', 'В процессе обучения'), ('COMP', 'Завершила обучение'), ('NCOM', 'Отменена')], default='NEW', max_length=4, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='competence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='education_centers.competence', verbose_name='Компетенция'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('employment_type', models.CharField(blank=True, choices=[('STFF', 'Штатный педагогический сотрудник'), ('TTRC', 'Привлеченный педагогический работник')], max_length=4, null=True, verbose_name='Тип трудоустройства')),
                ('education_level', models.CharField(blank=True, choices=[('STFF', 'Штатный педагогический сотрудник'), ('TTRC', 'Привлеченный педагогический работник')], max_length=4, null=True, verbose_name='Уровень образования')),
                ('experience', models.TextField(blank=True, null=True, verbose_name='Наличие опыта')),
                ('license_issued_by', models.TextField(blank=True, null=True, verbose_name='Кем выдана обр. лизенция (творический падеж)')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='education_centers.educationcenter', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Педагог',
                'verbose_name_plural': 'Педагоги',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('position', models.CharField(max_length=50, verbose_name='Должность')),
                ('first_name_r', models.CharField(max_length=30, verbose_name='Имя (род)')),
                ('middle_name_r', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество (род)')),
                ('last_name_r', models.CharField(max_length=30, verbose_name='Фамилия (род)')),
                ('position_r', models.CharField(max_length=50, verbose_name='Должность (род)')),
                ('phone', models.CharField(max_length=120, verbose_name='Телефон(-ы)')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='education_centers.educationcenter', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Сотрудник (контрагента)',
                'verbose_name_plural': 'Сотрудники (контрагента)',
            },
        ),
    ]
