# Generated by Django 3.2.8 on 2023-05-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0021_auto_20230503_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationcenter',
            name='entity_sex',
            field=models.CharField(blank=True, choices=[('M', 'Женский'), ('N', 'Средний')], max_length=4, null=True, verbose_name='Род для юр. лица'),
        ),
        migrations.AddField(
            model_name='educationcenter',
            name='home_city',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='educationcenter',
            name='is_ndc',
            field=models.BooleanField(default=False, verbose_name='Платит НДС?'),
        ),
        migrations.AddField(
            model_name='educationcenter',
            name='license_issued_by',
            field=models.TextField(blank=True, null=True, verbose_name='Кем выдана обр. лизенция (творический падеж)'),
        ),
        migrations.AddField(
            model_name='educationcenter',
            name='none_ndc_reason',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Основание работы без НДС'),
        ),
        migrations.AddField(
            model_name='educationcenter',
            name='short_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Краткое название организации'),
        ),
        migrations.AddField(
            model_name='educationcenter',
            name='short_name_r',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Краткое название организации (род.)'),
        ),
    ]
