# Generated by Django 3.2.8 on 2023-05-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0022_auto_20230503_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_head',
            field=models.BooleanField(default=False, verbose_name='Руководитель организации?'),
        ),
    ]
