# Generated by Django 3.2.8 on 2023-05-03 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0023_employee_is_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationprogram',
            name='ed_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='education_centers.educationcenter', verbose_name='Центр обучения'),
        ),
    ]
