# Generated by Django 3.2.8 on 2023-05-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0024_educationprogram_ed_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationprogram',
            name='education_type',
        ),
        migrations.AddField(
            model_name='competence',
            name='is_irpo',
            field=models.BooleanField(default=False, verbose_name='ИРПО?'),
        ),
        migrations.AlterField(
            model_name='educationprogram',
            name='entry_requirements',
            field=models.CharField(blank=True, choices=[('NDC', 'Без образования'), ('SPO', 'Cреднее профессиональное образование')], max_length=4, null=True, verbose_name='Входные требования'),
        ),
    ]
