# Generated by Django 3.2.8 on 2023-05-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0025_auto_20230503_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='license_issued_by',
        ),
        migrations.AddField(
            model_name='teacher',
            name='additional_education',
            field=models.TextField(blank=True, null=True, verbose_name='Наличие доп. проф. образования по профилю программы за последние 3 года'),
        ),
    ]
