# Generated by Django 4.2.6 on 2024-07-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0026_alter_educationprogram_employer_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationprogram',
            name='is_atlas',
            field=models.BooleanField(default=False, verbose_name='Атлас?'),
        ),
    ]
