# Generated by Django 3.2.8 on 2023-05-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0026_auto_20230504_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Название мастерской'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='education_level',
            field=models.CharField(blank=True, choices=[('VO', 'Высшее образование'), ('SPO', 'Среднее профессиональное образование')], max_length=4, null=True, verbose_name='Уровень образования'),
        ),
    ]
