# Generated by Django 3.2.8 on 2023-05-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0027_auto_20230504_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='equipment',
            field=models.TextField(blank=True, null=True, verbose_name='Оборудование'),
        ),
    ]
