# Generated by Django 3.2.8 on 2023-05-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0028_workshop_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationcenter',
            name='home_city',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='educationcenter',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Краткое название организации'),
        ),
        migrations.AlterField(
            model_name='educationcenter',
            name='short_name_r',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Краткое название организации (род.)'),
        ),
    ]
