# Generated by Django 3.2.8 on 2023-05-04 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0029_auto_20230504_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationcenter',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='educationcenter',
            name='none_ndc_reason',
        ),
        migrations.RemoveField(
            model_name='educationcenter',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='educationcenter',
            name='short_name_r',
        ),
    ]
