# Generated by Django 4.2.6 on 2024-07-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0029_group_is_atlas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=750, verbose_name='Номер группы'),
        ),
    ]
