# Generated by Django 4.2.6 on 2024-07-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0030_alter_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=750, verbose_name='Программа'),
        ),
    ]
