# Generated by Django 3.2.8 on 2023-05-04 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education_centers', '0030_auto_20230504_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationcenter',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='education_centers', to=settings.AUTH_USER_MODEL, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='educationcenter',
            name='none_ndc_reason',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Основание работы без НДС'),
        ),
        migrations.AddField(
            model_name='educationcenter',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Краткое название организации'),
        ),
        migrations.AddField(
            model_name='educationcenter',
            name='short_name_r',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Краткое название организации (род.)'),
        ),
    ]
