# Generated by Django 3.2.8 on 2023-05-04 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0031_auto_20230504_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationcenter',
            name='home_city',
        ),
    ]
