# Generated by Django 4.2.6 on 2024-08-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0031_alter_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_certified',
            field=models.BooleanField(default=False, verbose_name='Имеет профессиональные сертификации по компетенции?'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_experienced',
            field=models.BooleanField(default=False, verbose_name='Обладает опытом по тематике мероприятия?'),
        ),
    ]
