# Generated by Django 3.2.8 on 2023-05-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0032_remove_educationcenter_home_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationcenter',
            name='home_city',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Город'),
        ),
    ]
