# Generated by Django 3.2.8 on 2023-05-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0033_educationcenter_home_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationcenter',
            name='ed_license',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Образовательная лизенция (серия, номер, дата, срок действия)'),
        ),
        migrations.AlterField(
            model_name='educationcenter',
            name='license_issued_by',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Кем выдана обр. лизенция (творический падеж)'),
        ),
    ]
