# Generated by Django 4.2.6 on 2024-09-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0033_teacher_email_teacher_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationprogram',
            name='atlas_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID программы (Атлас)'),
        ),
    ]
