# Generated by Django 4.2.6 on 2024-09-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0034_educationprogram_atlas_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationprogram',
            name='atlas_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ID программы (Атлас)'),
        ),
    ]
