# Generated by Django 3.2.8 on 2023-05-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0034_auto_20230504_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='programs',
            field=models.ManyToManyField(related_name='teachers', to='education_centers.EducationProgram', verbose_name='программы'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='programs',
            field=models.ManyToManyField(related_name='workshops', to='education_centers.EducationProgram', verbose_name='программы'),
        ),
    ]
