# Generated by Django 3.2.8 on 2023-05-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0035_auto_20230504_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='workshops', to='education_centers.EducationProgram', verbose_name='программы'),
        ),
    ]
