# Generated by Django 4.2.6 on 2024-11-05 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0035_alter_educationprogram_atlas_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDocEdu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('full_name', models.CharField(max_length=500, verbose_name='ФИО')),
                ('passport_series', models.CharField(max_length=500, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(max_length=500, verbose_name='Номер паспорта')),
                ('passport_issued_by', models.CharField(max_length=500, verbose_name='Кем выдан паспорт')),
                ('passport_issued_date', models.DateField(verbose_name='Дата выдачи паспорта')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('phone', models.CharField(blank=True, max_length=120, null=True, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Документ заявки',
                'verbose_name_plural': 'Документы заявок',
            },
        ),
    ]
