# Generated by Django 4.2.6 on 2024-11-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0036_applicationdocedu'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdocedu',
            name='signed_file',
            field=models.FileField(blank=True, null=True, upload_to='media/application_docs/', verbose_name='Подписанный документ'),
        ),
    ]
