# Generated by Django 3.2.8 on 2023-05-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0037_alter_workshop_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Название компетенции'),
        ),
        migrations.AlterField(
            model_name='educationprogram',
            name='profession',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Профессия'),
        ),
    ]
