# Generated by Django 3.2.8 on 2023-05-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0038_auto_20230505_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='is_irpo',
            field=models.BooleanField(default=True, verbose_name='ИРПО?'),
        ),
        migrations.AlterField(
            model_name='educationprogram',
            name='entry_requirements',
            field=models.CharField(blank=True, choices=[('NDC', 'Без образования'), ('SPO', 'Среднее профессиональное образование')], max_length=4, null=True, verbose_name='Входные требования'),
        ),
    ]
