# Generated by Django 4.2.6 on 2024-11-05 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0038_applicationdocedu_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationdocedu',
            name='passport_number',
        ),
        migrations.AlterField(
            model_name='applicationdocedu',
            name='passport_series',
            field=models.CharField(max_length=500, verbose_name='Серия и номер паспорта'),
        ),
    ]
