# Generated by Django 3.2.8 on 2023-05-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0039_auto_20230510_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='bank_inn',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='bank_kpp',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='personal_account_number',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Лицевой счёт'),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='okved',
            field=models.CharField(max_length=250, verbose_name='ОКВЭД'),
        ),
    ]
