# Generated by Django 4.2.6 on 2024-11-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0039_remove_applicationdocedu_passport_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdocedu',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/application_docs/', verbose_name='документ'),
        ),
    ]
