# Generated by Django 4.2.6 on 2024-11-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0040_applicationdocedu_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdocedu',
            name='passport_issued_date',
            field=models.DateTimeField(verbose_name='Дата выдачи паспорта'),
        ),
    ]
