# Generated by Django 3.2.8 on 2023-05-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0040_auto_20230515_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='position',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Ученая степень/должность'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='classes_type',
            field=models.CharField(blank=True, choices=[('T', 'Теоретические занятия'), ('P', 'Практические занятия'), ('TP', 'Практические и теоретические занятия')], max_length=4, null=True, verbose_name='Вид занятий'),
        ),
    ]
