# Generated by Django 3.2.8 on 2023-05-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0041_auto_20230515_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='education_major',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Специальность'),
        ),
    ]
