# Generated by Django 3.2.8 on 2023-05-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0042_teacher_education_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ученая степень/должность'),
        ),
    ]
