# Generated by Django 4.2.6 on 2024-11-05 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0042_applicationdocedu_citizen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationdocedu',
            name='email',
        ),
        migrations.RemoveField(
            model_name='applicationdocedu',
            name='phone',
        ),
    ]
