# Generated by Django 3.2.8 on 2023-05-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0043_alter_teacher_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='bank_inn',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Банк ИНН'),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='bank_kpp',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Банк КПП'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=150, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position_r',
            field=models.CharField(max_length=150, verbose_name='Должность (род)'),
        ),
    ]
