# Generated by Django 3.2.8 on 2023-05-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0044_auto_20230518_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationprogram',
            name='is_bvb',
            field=models.BooleanField(default=False, verbose_name='Проф проба?'),
        ),
    ]
