# Generated by Django 3.2.8 on 2023-05-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0046_auto_20230527_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='bvb_experience',
            field=models.TextField(blank=True, null=True, verbose_name='Наличие профессиональных сертификаций'),
        ),
    ]
