# Generated by Django 3.2.8 on 2023-06-16 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0047_teacher_bvb_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='education_project',
        ),
    ]
