# Generated by Django 3.2.8 on 2023-06-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0005_auto_20230616_1519'),
        ('education_centers', '0048_remove_group_education_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationcenterhead',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='competence',
            name='block',
        ),
        migrations.RemoveField(
            model_name='competence',
            name='competence_stage',
        ),
        migrations.RemoveField(
            model_name='competence',
            name='competence_type',
        ),
        migrations.AddField(
            model_name='competence',
            name='is_worldskills',
            field=models.BooleanField(default=True, verbose_name='ВС?'),
        ),
        migrations.AlterField(
            model_name='educationcenter',
            name='entity_sex',
            field=models.CharField(blank=True, choices=[('ML', 'Мужской'), ('M', 'Женский'), ('N', 'Средний')], max_length=4, null=True, verbose_name='Род для юр. лица'),
        ),
        migrations.DeleteModel(
            name='EducationCenterGroup',
        ),
        migrations.DeleteModel(
            name='EducationCenterHead',
        ),
    ]
