# Generated by Django 4.2.6 on 2024-01-27 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0033_remove_partnerevent_partner'),
        ('regions', '0004_citytype_region_teradministration_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
