# Generated by Django 3.2.8 on 2023-05-24 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education_centers', '0044_auto_20230518_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketProjectYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='year')),
                ('programs', models.ManyToManyField(blank=True, related_name='ticket_project_years', to='education_centers.EducationProgram', verbose_name='Программы')),
            ],
            options={
                'verbose_name': 'Год проекта (БВБ)',
                'verbose_name_plural': 'Годы проекта (БВБ)',
            },
        ),
        migrations.CreateModel(
            name='EducationCenterTicketProjectYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appl_docs_link', models.TextField(default='', verbose_name='Ссылка на комп. документов')),
                ('stage', models.CharField(choices=[('FLLNG', 'заполнение заявки'), ('VRFD', 'заявка проверена'), ('FRMD', 'документы сформированы'), ('PRVD', 'заявка принята')], default='FLLNG', max_length=5, verbose_name='Работа с заявкой')),
                ('quota', models.IntegerField(default=0, verbose_name='Квота')),
                ('ed_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_project_years', to='education_centers.educationcenter', verbose_name='Центр обучения')),
                ('project_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ed_centers', to='future_ticket.ticketprojectyear', verbose_name='Год проекта (БВБ)')),
            ],
            options={
                'verbose_name': 'Данные колледжа на год (БВБ)',
                'verbose_name_plural': 'Данные колледжей на годы (БВБ)',
            },
        ),
    ]
