# Generated by Django 3.2.8 on 2023-08-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0001_squashed_0028_contractorsdocumentticket_documenttypeticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edcenterticketindicator',
            name='value',
            field=models.CharField(max_length=25, verbose_name='Значение показателя'),
        ),
        migrations.AlterField(
            model_name='educationcenterticketprojectyear',
            name='stage',
            field=models.CharField(choices=[('FLLNG', 'заполнение'), ('FLLD', 'на проверке'), ('RWRK', 'отправлена на доработку'), ('VRFD', 'проверена'), ('FRMD', 'сформирована'), ('DWNLD', 'подгружена'), ('PRVD', 'принята'), ('FNSHD', 'ПКО пройден')], default='FLLNG', max_length=5, verbose_name='Работа с заявкой'),
        ),
    ]
