# Generated by Django 3.2.8 on 2023-05-25 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0045_educationprogram_is_bvb'),
        ('future_ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketProjectPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50, verbose_name='Название позиции')),
                ('is_basis_needed', models.BooleanField(default=False, verbose_name='Нужно основание?')),
                ('project_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='future_ticket.ticketprojectyear', verbose_name='Год проекта')),
            ],
            options={
                'verbose_name': 'Позиция в проекте (БВБ)',
                'verbose_name_plural': 'Позиции в проекте (БВБ)',
            },
        ),
        migrations.CreateModel(
            name='TicketIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Показатель эффективности')),
                ('is_free_form', models.BooleanField(default=False, verbose_name='Свободная форма?')),
                ('year', models.IntegerField(verbose_name='Показатель за (год)')),
                ('project_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='future_ticket.ticketprojectyear', verbose_name='Год проекта')),
            ],
            options={
                'verbose_name': 'Показатель эффективности (БВБ)',
                'verbose_name_plural': 'Показатели эффективности (БВБ)',
            },
        ),
        migrations.CreateModel(
            name='TicketEdCenterEmployeePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acts_basis', models.CharField(blank=True, max_length=500, null=True, verbose_name='Действует на основании')),
                ('ed_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_positions_employees', to='education_centers.educationcenter', verbose_name='Центр обучения')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_positions', to='education_centers.employee', verbose_name='Сотрудник')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_positions_employees', to='future_ticket.ticketprojectposition', verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Роль сотрудника (БВБ)',
                'verbose_name_plural': 'Роли сотрудников (БВБ)',
            },
        ),
        migrations.CreateModel(
            name='EdCenterTicketIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_2021', models.CharField(max_length=25, verbose_name='Значение показателя (2021)')),
                ('value_2022', models.CharField(max_length=25, verbose_name='Значение показателя (2022)')),
                ('free_form_value', models.TextField(blank=True, default='', null=True, verbose_name='Значение (свободная форма)')),
                ('ed_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_indicators', to='education_centers.educationcenter', verbose_name='Центр обучения')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ed_centers', to='future_ticket.ticketindicator', verbose_name='Показатель')),
            ],
            options={
                'verbose_name': 'Показатель эффективности (ЦО БВБ)',
                'verbose_name_plural': 'Показатели эффективности (ЦО БВБ)',
            },
        ),
    ]
