# Generated by Django 4.2.5 on 2023-09-05 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0002_auto_20230826_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketprogram',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketprogram',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
