# Generated by Django 3.2.8 on 2023-05-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0002_edcenterticketindicator_ticketedcenteremployeeposition_ticketindicator_ticketprojectposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketindicator',
            name='year',
        ),
        migrations.AlterField(
            model_name='ticketprojectyear',
            name='year',
            field=models.IntegerField(verbose_name='год'),
        ),
    ]
