# Generated by Django 3.2.8 on 2023-05-25 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0003_auto_20230525_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketedcenteremployeeposition',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions_employees', to='future_ticket.ticketprojectposition', verbose_name='Позиция'),
        ),
    ]
