# Generated by Django 3.2.8 on 2023-05-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0004_alter_ticketedcenteremployeeposition_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationcenterticketprojectyear',
            name='step_1_check',
            field=models.BooleanField(default=False, verbose_name='Шаг 1. Проверка'),
        ),
        migrations.AddField(
            model_name='educationcenterticketprojectyear',
            name='step_1_commentary',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Шаг 1. Комментарий'),
        ),
        migrations.AddField(
            model_name='educationcenterticketprojectyear',
            name='step_2_check',
            field=models.BooleanField(default=False, verbose_name='Шаг 2. Проверка'),
        ),
        migrations.AddField(
            model_name='educationcenterticketprojectyear',
            name='step_2_commentary',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Шаг 2. Комментарий'),
        ),
        migrations.AddField(
            model_name='educationcenterticketprojectyear',
            name='step_3_check',
            field=models.BooleanField(default=False, verbose_name='Шаг 3. Проверка'),
        ),
        migrations.AddField(
            model_name='educationcenterticketprojectyear',
            name='step_3_commentary',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Шаг 3. Комментарий'),
        ),
        migrations.AddField(
            model_name='educationcenterticketprojectyear',
            name='step_4_check',
            field=models.BooleanField(default=False, verbose_name='Шаг 4. Проверка'),
        ),
        migrations.AddField(
            model_name='educationcenterticketprojectyear',
            name='step_4_commentary',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Шаг 4. Комментарий'),
        ),
        migrations.AddField(
            model_name='educationcenterticketprojectyear',
            name='step_5_check',
            field=models.BooleanField(default=False, verbose_name='Шаг 5. Проверка'),
        ),
        migrations.AddField(
            model_name='educationcenterticketprojectyear',
            name='step_5_commentary',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Шаг 5. Комментарий'),
        ),
        migrations.AddField(
            model_name='educationcenterticketprojectyear',
            name='step_6_check',
            field=models.BooleanField(default=False, verbose_name='Шаг 6. Проверка'),
        ),
        migrations.AddField(
            model_name='educationcenterticketprojectyear',
            name='step_6_commentary',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Шаг 6. Комментарий'),
        ),
    ]
