# Generated by Django 3.2.8 on 2023-09-19 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0001_squashed_0006_remove_citizen_aplication_stages'),
        ('future_ticket', '0004_eventscycle_studentbvb_ticketevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbvb',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Скрыт?'),
        ),
        migrations.AddField(
            model_name='ticketquota',
            name='completed_quota',
            field=models.IntegerField(default=0, verbose_name='Выполненная квота'),
        ),
        migrations.AddField(
            model_name='ticketquota',
            name='reserved_quota',
            field=models.IntegerField(default=0, verbose_name='Зарезервированая квота'),
        ),
        migrations.AlterField(
            model_name='studentbvb',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizens.school', verbose_name='Школа'),
        ),
    ]
