# Generated by Django 3.2.8 on 2023-05-27 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0120_auto_20230527_1845'),
        ('education_centers', '0046_auto_20230527_1845'),
        ('future_ticket', '0005_auto_20230525_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfEnviroment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название среды')),
            ],
            options={
                'verbose_name': 'Профессиональная среда',
                'verbose_name_plural': 'Профессиональные среды',
            },
        ),
        migrations.CreateModel(
            name='ProgramAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=120, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='education_centers.teacher', verbose_name='Педагог')),
            ],
            options={
                'verbose_name': 'Автор программы (БВБ)',
                'verbose_name_plural': 'Авторы программ (БВБ)',
            },
        ),
        migrations.CreateModel(
            name='TicketProfession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название профессии')),
                ('prof_enviroment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profession', to='future_ticket.profenviroment', verbose_name='Среда')),
            ],
            options={
                'verbose_name': 'Профессия (БВБ)',
                'verbose_name_plural': 'Профессии (БВБ)',
            },
        ),
        migrations.CreateModel(
            name='TicketProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_federal', models.BooleanField(default=False, verbose_name='Федеральная?')),
                ('education_form', models.CharField(choices=[('FLL', 'Очная'), ('FLLLN', 'Очная с применением ДОТ ')], max_length=5, verbose_name='Форма обучения')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткое описание задания')),
                ('age_group', models.CharField(choices=[('NGST', '6-7 класс'), ('MDDL', '8-9 класс'), ('LDST', '10-11 класс')], max_length=4, verbose_name='Возрастная категория')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='future_ticket.programauthor', verbose_name='Автор программы')),
                ('disability_types', models.ManyToManyField(blank=True, to='users.DisabilityType', verbose_name='ОВЗ')),
                ('ed_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_programs', to='education_centers.educationcenter', verbose_name='Центр обучения')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='programs', to='future_ticket.ticketprofession', verbose_name='Профессия')),
                ('programs', models.ManyToManyField(related_name='ticket_programs', to='education_centers.Teacher', verbose_name='педагоги')),
            ],
            options={
                'verbose_name': 'Программа (БВБ)',
                'verbose_name_plural': 'Программы (БВБ)',
            },
        ),
    ]
