# Generated by Django 3.2.8 on 2023-05-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0046_auto_20230527_1845'),
        ('future_ticket', '0006_profenviroment_programauthor_ticketprofession_ticketprogram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketprogram',
            old_name='programs',
            new_name='teachers',
        ),
        migrations.AddField(
            model_name='ticketprogram',
            name='workshops',
            field=models.ManyToManyField(related_name='ticket_worshops', to='education_centers.Workshop', verbose_name='аудитории'),
        ),
    ]
