# Generated by Django 3.2.8 on 2023-09-19 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0006_eventscycle_project_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventscycle',
            name='status',
            field=models.CharField(choices=[('REG', 'Регистрация'), ('CHCK', 'Проверка'), ('HSTNG', 'В процессе'), ('END', 'Завершено')], default='REG', max_length=6, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='studentbvb',
            name='is_attend',
            field=models.BooleanField(default=False, verbose_name='Присутствовал?'),
        ),
        migrations.AddField(
            model_name='ticketevent',
            name='profession',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='future_ticket.ticketprofession', verbose_name='Профессия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketevent',
            name='status',
            field=models.CharField(choices=[('CRTD', 'Создана'), ('LOAD', 'Участники загружены'), ('HSTD', 'Проведенна'), ('CHCKD', 'Проверенна')], default='CRTD', max_length=6, verbose_name='Статус'),
        ),
    ]
