# Generated by Django 3.2.8 on 2023-05-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0046_auto_20230527_1845'),
        ('future_ticket', '0007_auto_20230527_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketprogram',
            name='workshops',
            field=models.ManyToManyField(related_name='ticket_programs', to='education_centers.Workshop', verbose_name='аудитории'),
        ),
    ]
