# Generated by Django 3.2.8 on 2023-09-19 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0007_auto_20230919_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketevent',
            name='quota',
        ),
        migrations.CreateModel(
            name='QuotaEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_quota', models.IntegerField(verbose_name='Колво участников')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='future_ticket.ticketevent', verbose_name='Квота')),
                ('quota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='future_ticket.ticketquota', verbose_name='Квота')),
            ],
        ),
    ]
