# Generated by Django 3.2.8 on 2023-09-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0008_auto_20230919_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketquota',
            name='free_quota',
            field=models.IntegerField(default=0, verbose_name='Свободная квота'),
        ),
        migrations.AlterField(
            model_name='ticketevent',
            name='participants_limit',
            field=models.IntegerField(default=0, verbose_name='Колво участников'),
        ),
    ]
