# Generated by Django 3.2.8 on 2023-05-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0009_auto_20230529_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationcenterticketprojectyear',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='ticket_centers_project_years', to='future_ticket.TicketProgram', verbose_name='Программы'),
        ),
        migrations.AlterField(
            model_name='ticketprojectyear',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='ticket_project_years', to='future_ticket.TicketProgram', verbose_name='Программы'),
        ),
    ]
