# Generated by Django 3.2.8 on 2023-05-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0010_auto_20230529_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название профессии')),
            ],
            options={
                'verbose_name': 'Возрастная группа (БВБ)',
                'verbose_name_plural': 'Возрастные группы (БВБ)',
            },
        ),
        migrations.RemoveField(
            model_name='ticketprogram',
            name='age_group',
        ),
        migrations.AlterField(
            model_name='ticketprogram',
            name='education_form',
            field=models.CharField(choices=[('FLL', 'Очный'), ('FLLLN', 'Очный с применением ДОТ')], max_length=5, verbose_name='Формат обучения'),
        ),
        migrations.AddField(
            model_name='ticketprogram',
            name='age_groups',
            field=models.ManyToManyField(related_name='programs', to='future_ticket.AgeGroup', verbose_name='Возрастная категория'),
        ),
    ]
