# Generated by Django 3.2.8 on 2023-09-20 15:31

from django.db import migrations, models

from future_ticket.models import TicketQuota

def set_free_quota(apps, schema_editor):
    for quota in TicketQuota.objects.all():
        quota.free_quota = quota.approved_value
        quota.save()

class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0010_alter_ticketquota_free_quota'),
    ]

    operations = [
        migrations.RunPython(set_free_quota)
    ]

    

