# Generated by Django 3.2.8 on 2023-05-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0011_auto_20230530_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketprogram',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание задания'),
        ),
    ]
