# Generated by Django 3.2.8 on 2023-05-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0012_alter_ticketprogram_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edcenterticketindicator',
            name='value_2021',
        ),
        migrations.RemoveField(
            model_name='edcenterticketindicator',
            name='value_2022',
        ),
        migrations.AddField(
            model_name='edcenterticketindicator',
            name='value',
            field=models.CharField(default='', max_length=25, verbose_name='Значение показателя'),
            preserve_default=False,
        ),
    ]
