# Generated by Django 3.2.8 on 2023-05-31 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0004_auto_20230530_1549'),
        ('education_centers', '0046_auto_20230527_1845'),
        ('future_ticket', '0013_auto_20230531_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketFullQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_quota', models.IntegerField(default=0, verbose_name='Полная квота')),
                ('federal_quota', models.IntegerField(default=0, verbose_name='Федеральная квота')),
            ],
            options={
                'verbose_name': 'Квота региона',
                'verbose_name_plural': 'Квоты региона',
            },
        ),
        migrations.AlterModelOptions(
            name='agegroup',
            options={'verbose_name': 'Возрастная группа', 'verbose_name_plural': 'Возрастные группы'},
        ),
        migrations.AlterModelOptions(
            name='edcenterticketindicator',
            options={'verbose_name': 'Показатель эффективности (ЦО)', 'verbose_name_plural': 'Показатели эффективности (ЦО)'},
        ),
        migrations.AlterModelOptions(
            name='educationcenterticketprojectyear',
            options={'verbose_name': 'Данные колледжа на год', 'verbose_name_plural': 'Данные колледжей на годы'},
        ),
        migrations.AlterModelOptions(
            name='programauthor',
            options={'verbose_name': 'Автор программы', 'verbose_name_plural': 'Авторы программ'},
        ),
        migrations.AlterModelOptions(
            name='ticketedcenteremployeeposition',
            options={'verbose_name': 'Роль сотрудника', 'verbose_name_plural': 'Роли сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='ticketindicator',
            options={'verbose_name': 'Показатель эффективности', 'verbose_name_plural': 'Показатели эффективности'},
        ),
        migrations.AlterModelOptions(
            name='ticketprofession',
            options={'verbose_name': 'Профессия', 'verbose_name_plural': 'Профессии'},
        ),
        migrations.AlterModelOptions(
            name='ticketprogram',
            options={'verbose_name': 'Программа', 'verbose_name_plural': 'Программы'},
        ),
        migrations.AlterModelOptions(
            name='ticketprojectposition',
            options={'verbose_name': 'Позиция в проекте', 'verbose_name_plural': 'Позиции в проекте'},
        ),
        migrations.AlterModelOptions(
            name='ticketprojectyear',
            options={'verbose_name': 'Год проекта', 'verbose_name_plural': 'Годы проекта'},
        ),
        migrations.CreateModel(
            name='TicketQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_federal', models.BooleanField(default=False, verbose_name='Федеральная?')),
                ('value', models.IntegerField(default=0, verbose_name='Квота')),
                ('ed_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_quotas', to='education_centers.educationcenter', verbose_name='Центр обучения')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='future_ticket.ticketprofession', verbose_name='Профессия')),
                ('qouta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='future_ticket.ticketfullquota', verbose_name='Квота')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_quotas', to='citizens.school', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Квота',
                'verbose_name_plural': 'Квоты',
            },
        ),
        migrations.AddField(
            model_name='ticketfullquota',
            name='project_year',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to='future_ticket.ticketprojectyear', verbose_name='Год проекта'),
        ),
    ]
