# Generated by Django 3.2.8 on 2023-09-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0013_alter_ticketquota_free_quota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventscycle',
            name='status',
            field=models.CharField(choices=[('REG', 'Регистрация'), ('CHCK', 'Проверка и коррекция'), ('HSTNG', 'В процессе'), ('END', 'Завершено')], default='REG', max_length=6, verbose_name='Статус'),
        ),
    ]
