# Generated by Django 3.2.8 on 2023-05-31 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0014_auto_20230531_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketquota',
            old_name='qouta',
            new_name='quota',
        ),
    ]
