# Generated by Django 3.2.8 on 2023-09-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0014_alter_eventscycle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventscycle',
            name='end_period_date',
            field=models.DateField(verbose_name='Конец проведения мероприятий'),
        ),
        migrations.AlterField(
            model_name='eventscycle',
            name='end_reg_date',
            field=models.DateField(verbose_name='Дата окончания регистрации'),
        ),
        migrations.AlterField(
            model_name='eventscycle',
            name='start_period_date',
            field=models.DateField(verbose_name='Старт проведения мероприятий'),
        ),
    ]
