# Generated by Django 3.2.8 on 2023-10-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0015_auto_20230922_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentbvb',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='studentbvb',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='studentbvb',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='studentbvb',
            name='full_name',
            field=models.CharField(default=1, max_length=200, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
