# Generated by Django 3.2.8 on 2023-05-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0015_rename_qouta_ticketquota_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketprojectyear',
            name='is_disability',
            field=models.BooleanField(default=False, verbose_name='ОВЗ?'),
        ),
    ]
