# Generated by Django 3.2.8 on 2023-10-02 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0016_auto_20231002_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketevent',
            name='participants',
        ),
        migrations.AddField(
            model_name='studentbvb',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='future_ticket.ticketevent', verbose_name='Мероприятие'),
            preserve_default=False,
        ),
    ]
