# Generated by Django 3.2.8 on 2023-05-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0016_ticketprojectyear_is_disability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketprojectyear',
            name='is_disability',
        ),
        migrations.AddField(
            model_name='educationcenterticketprojectyear',
            name='is_disability',
            field=models.BooleanField(default=False, verbose_name='ОВЗ?'),
        ),
    ]
