# Generated by Django 3.2.8 on 2023-10-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0017_auto_20231002_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbvb',
            name='is_attend',
            field=models.BooleanField(default=True, verbose_name='Присутствовал?'),
        ),
    ]
