# Generated by Django 3.2.8 on 2023-06-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0017_auto_20230531_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketprofession',
            name='is_centers',
            field=models.BooleanField(default=False, verbose_name='Создана ЦО?'),
        ),
    ]
