# Generated by Django 3.2.8 on 2023-10-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0018_alter_studentbvb_is_attend'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventscycle',
            name='cycle_number',
            field=models.IntegerField(default=1, verbose_name='№ цикла'),
        ),
    ]
