# Generated by Django 3.2.8 on 2023-06-01 11:03

from django.db import migrations, models
import future_ticket.models


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0019_auto_20230601_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationcenterticketprojectyear',
            name='application_file',
            field=models.FileField(blank=True, null=True, upload_to=future_ticket.models.EducationCenterTicketProjectYear.doc_directory_path, verbose_name='Скан заявки'),
        ),
    ]
