# Generated by Django 4.2 on 2023-10-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0019_eventscycle_cycle_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketevent',
            name='photo_link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Фото с профпробы'),
        ),
    ]
