# Generated by Django 3.2.8 on 2023-06-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0020_educationcenterticketprojectyear_application_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationcenterticketprojectyear',
            name='appl_track_number',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название позиции'),
        ),
    ]
