# Generated by Django 4.2 on 2023-11-08 06:56

from django.db import migrations, models
import future_ticket.models


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0021_alter_ticketevent_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolprojectyear',
            options={'verbose_name': 'Школа (ответственный)', 'verbose_name_plural': 'Школы (ответственные)'},
        ),
        migrations.AddField(
            model_name='ticketevent',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='educationcenterticketprojectyear',
            name='application_file',
            field=models.FileField(blank=True, null=True, upload_to=future_ticket.models.EducationCenterTicketProjectYear.doc_directory_path, verbose_name='Скан заявки'),
        ),
        migrations.AlterField(
            model_name='educationcenterticketprojectyear',
            name='stage',
            field=models.CharField(choices=[('FLLNG', 'заполнение'), ('FLLD', 'на проверке'), ('RWRK', 'отправлена на доработку'), ('VRFD', 'проверена'), ('FRMD', 'сформирована'), ('DWNLD', 'подгружена'), ('PRVD', 'принята'), ('FNSHD', 'ПКО пройден'), ('ACT', 'Акт сформирован'), ('ACTS', 'Акт подписан'), ('NVC', 'Счёт подгружен'), ('NVCP', 'Счёт оплачен')], default='FLLNG', max_length=5, verbose_name='Работа с заявкой'),
        ),
    ]
