# Generated by Django 3.2.8 on 2023-06-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0021_educationcenterticketprojectyear_appl_track_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationcenterticketprojectyear',
            name='step_8_check',
            field=models.BooleanField(default=False, verbose_name='Шаг 8. Проверка'),
        ),
        migrations.AddField(
            model_name='educationcenterticketprojectyear',
            name='step_8_commentary',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Шаг 8. Комментарий'),
        ),
        migrations.AlterField(
            model_name='educationcenterticketprojectyear',
            name='appl_track_number',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Трек номер'),
        ),
    ]
