# Generated by Django 4.2 on 2023-11-08 09:00

from django.db import migrations, models
import future_ticket.models


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0022_alter_schoolprojectyear_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationcenterticketprojectyear',
            name='application_file',
            field=models.FileField(blank=True, null=True, upload_to=future_ticket.models.EducationCenterTicketProjectYear.doc_directory_path, verbose_name='Скан заявки'),
        ),
        migrations.AlterField(
            model_name='ticketevent',
            name='start_time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Время начала'),
        ),
    ]
