# Generated by Django 3.2.8 on 2023-06-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0022_auto_20230601_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationcenterticketprojectyear',
            name='quota',
        ),
        migrations.AlterField(
            model_name='educationcenterticketprojectyear',
            name='appl_docs_link',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Ссылка на комп. документов'),
        ),
    ]
