# Generated by Django 4.2 on 2023-11-09 07:01

from django.db import migrations, models
import future_ticket.models


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0023_alter_educationcenterticketprojectyear_application_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationcenterticketprojectyear',
            name='act_file',
            field=models.FileField(blank=True, null=True, upload_to=future_ticket.models.EducationCenterTicketProjectYear.doc_dir_path, verbose_name='Подписанный акт'),
        ),
        migrations.AddField(
            model_name='educationcenterticketprojectyear',
            name='bill_file',
            field=models.FileField(blank=True, null=True, upload_to=future_ticket.models.EducationCenterTicketProjectYear.doc_dir_path, verbose_name='Счёт'),
        ),
        migrations.AlterField(
            model_name='educationcenterticketprojectyear',
            name='stage',
            field=models.CharField(choices=[('FLLNG', 'заполнение'), ('FLLD', 'на проверке'), ('RWRK', 'отправлена на доработку'), ('VRFD', 'проверена'), ('FRMD', 'сформирована'), ('DWNLD', 'подгружена'), ('PRVD', 'принята'), ('FNSHD', 'ПКО пройден'), ('ACT', 'Акт сформирован'), ('ACTS', 'Акт подписан'), ('NVC', 'Счёт и акт подгружены'), ('NVCP', 'Счёт оплачен')], default='FLLNG', max_length=5, verbose_name='Работа с заявкой'),
        ),
    ]
