# Generated by Django 3.2.8 on 2023-06-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0047_teacher_bvb_experience'),
        ('future_ticket', '0024_auto_20230602_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketquota',
            name='approved_value',
            field=models.IntegerField(default=0, verbose_name='Одобренная квота'),
        ),
        migrations.AlterField(
            model_name='educationcenterticketprojectyear',
            name='stage',
            field=models.CharField(choices=[('FLLNG', 'заполнение'), ('FLLD', 'на проверке'), ('RWRK', 'отправлена на доработку'), ('VRFD', 'проверена'), ('FRMD', 'сформирована'), ('DWNLD', 'подгружена'), ('PRVD', 'принята')], default='FLLNG', max_length=5, verbose_name='Работа с заявкой'),
        ),
        migrations.AlterField(
            model_name='ticketprogram',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='ticket_programs', to='education_centers.Teacher', verbose_name='педагоги'),
        ),
        migrations.AlterField(
            model_name='ticketprogram',
            name='workshops',
            field=models.ManyToManyField(blank=True, related_name='ticket_programs', to='education_centers.Workshop', verbose_name='аудитории'),
        ),
    ]
