# Generated by Django 4.2 on 2023-11-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0024_educationcenterticketprojectyear_act_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationcenterticketprojectyear',
            name='stage',
            field=models.CharField(choices=[('FLLNG', 'заполнение'), ('FLLD', 'на проверке'), ('RWRK', 'отправлена на доработку'), ('VRFD', 'проверена'), ('FRMD', 'сформирована'), ('DWNLD', 'подгружена'), ('PRVD', 'принята'), ('FNSHD', 'ПКО пройден'), ('ACT', 'Акт сформирован'), ('ACTS', 'Акт подписан'), ('NVC', 'Счёт и акт подгружены'), ('PNVC', 'Счёт и акт проверены'), ('NVCP', 'Счёт оплачен')], default='FLLNG', max_length=5, verbose_name='Работа с заявкой'),
        ),
    ]
