# Generated by Django 4.2 on 2023-12-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0025_alter_educationcenterticketprojectyear_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketevent',
            name='event_date',
            field=models.DateField(verbose_name='Дата проведения'),
        ),
    ]
