# Generated by Django 4.2 on 2023-12-07 13:10

from django.db import migrations, models
import future_ticket.models


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0026_alter_ticketevent_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationcenterticketprojectyear',
            name='ndc_bill_file',
            field=models.FileField(blank=True, null=True, upload_to=future_ticket.models.EducationCenterTicketProjectYear.doc_dir_path, verbose_name='Счёт-фактура'),
        ),
    ]
