# Generated by Django 3.2.8 on 2023-07-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0026_schoolprojectyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketprogram',
            name='age_groups',
            field=models.ManyToManyField(related_name='programs', to='future_ticket.AgeGroup', verbose_name='Возрастные категории'),
        ),
    ]
