# Generated by Django 4.2.6 on 2024-01-21 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_remove_contactpersone_company_and_more'),
        ('future_ticket', '0027_educationcenterticketprojectyear_ndc_bill_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название мероприятия')),
                ('description', models.TextField(default='', verbose_name='Описание мероприятия')),
                ('instruction', models.TextField(default='', verbose_name='Инструкция')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='organizations.organization', verbose_name='Организатор')),
            ],
            options={
                'verbose_name': 'Цикл проб',
                'verbose_name_plural': 'Циклы проб',
            },
        ),
    ]
