# Generated by Django 4.2.6 on 2024-01-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0028_partnerevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnerevent',
            old_name='email',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='partnerevent',
            old_name='phone',
            new_name='contact_phone',
        ),
        migrations.AddField(
            model_name='partnerevent',
            name='status',
            field=models.CharField(choices=[('CRT', 'Создана'), ('PRV', 'Одобрено')], default='CRT', max_length=6, verbose_name='Статус'),
        ),
    ]
