# Generated by Django 4.2.6 on 2024-01-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0029_rename_email_partnerevent_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerevent',
            name='contact',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Контактное лицо'),
        ),
    ]
