# Generated by Django 4.2.6 on 2024-01-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0030_partnerevent_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerevent',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Населённый пункт'),
        ),
    ]
