# Generated by Django 4.2.6 on 2024-01-27 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0031_partnerevent_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnerevent',
            options={'verbose_name': 'Партнёрское мероприятие', 'verbose_name_plural': 'Партнёрские мероприятия'},
        ),
    ]
