# Generated by Django 4.2.6 on 2024-01-27 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0032_alter_partnerevent_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerevent',
            name='partner',
        ),
    ]
