# Generated by Django 4.2.6 on 2024-01-27 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_organization'),
        ('future_ticket', '0033_remove_partnerevent_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerevent',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='users.organization', verbose_name='Организатор'),
        ),
    ]
