# Generated by Django 4.2.6 on 2024-01-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0035_alter_partnerevent_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerevent',
            name='period',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Период проведения'),
        ),
        migrations.AddField(
            model_name='partnerevent',
            name='signup_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на запись'),
        ),
    ]
