# Generated by Django 4.2.6 on 2024-02-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0036_partnerevent_period_partnerevent_signup_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerevent',
            name='instruction',
            field=models.TextField(blank=True, default='', verbose_name='Инструкция'),
        ),
    ]
