# Generated by Django 4.2.6 on 2024-03-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0005_delete_organization'),
        ('future_ticket', '0037_alter_partnerevent_instruction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerevent',
            name='city',
        ),
        migrations.AddField(
            model_name='partnerevent',
            name='cities',
            field=models.ManyToManyField(blank=True, related_name='partner_events', to='regions.city', verbose_name='Территории проведения'),
        ),
    ]
