# Generated by Django 4.2.6 on 2024-08-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0041_alter_educationcenterticketprojectyear_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationcenterticketprojectyear',
            name='locked_quota',
            field=models.IntegerField(default=0, verbose_name='Израсходованная квота ЦО'),
        ),
        migrations.AlterField(
            model_name='educationcenterticketprojectyear',
            name='quota',
            field=models.IntegerField(default=0, verbose_name='Квота ЦО'),
        ),
    ]
