# Generated by Django 4.2.6 on 2024-08-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0043_ticketprofession_is_2024_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profenviroment',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Название среды'),
        ),
    ]
