# Generated by Django 4.2.6 on 2024-11-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_ticket', '0044_alter_profenviroment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotaevent',
            name='completed_quota',
            field=models.IntegerField(default=0, verbose_name='Колво участников (выполнено)'),
            preserve_default=False,
        ),
    ]
