name: Testing
on: push

jobs:
  test_application:
    runs-on: ubuntu-latest
    steps:
    – uses: actions/cheakout@v2
    – name: Run Django unit tests
      run:
      pip3 install --user django
      python3 manage.py test --keepdb vocational_guidance
 