name: Django CI

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]
    
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: mysql
        ports: ['3306:3306', '8000:8000']
  
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Migrations
      run: python manage.py migrate
      env: 
        SECRET_KEY: y!*pq182!%5tt!f(0176(2fbf1qx^5-hl=6it!2fu3#gfv2_w+
        DATABASE_NAME: mysql
        DATABASE_USER: root
        DATABASE_PASS: password
        DATABASE_HOST: 127.0.0.1
        DATABASE_PORT: ''
        ALLOWED_HOSTS: "127.0.0.1 localhost"
        CSRF_TRUSTED_ORIGINS: 'https://copp63-coordinator.ru '
        DEBUG: true
        STATIC_URL: '/copp163_coordinator/static/'
        MEDIA_URL: '/copp163_coordinator/media/'
        DBPORT: ${{ job.services.mysql.ports[3306] }}
    - name: Run Tests
      run: |
        python manage.py test
      env: 
        SECRET_KEY: y!*pq182!%5tt!f(0176(2fbf1qx^5-hl=6it!2fu3#gfv2_w+
        DATABASE_NAME: mysql
        DATABASE_USER: root
        DATABASE_PASS: password
        DATABASE_HOST: 127.0.0.1
        DATABASE_PORT: ''
        ALLOWED_HOSTS: "127.0.0.1 localhost"
        DEBUG: true
        STATIC_URL: '/copp163_coordinator/static/'
        MEDIA_URL: '/copp163_coordinator/media/'
        DBPORT: ${{ job.services.mysql.ports[3306] }}
