name: Django CI

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: mysql
        ports: ['3306:3306']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Migrations
      run: python manage.py migrate
      env:
        SECRET_KEY: django-insecure-r(h1v3!t+qib4ky91s=-eaxd@6ze)t+emce)+dq1%fgo$*s%6!
        DEBUG: true
        ALLOWED_HOSTS: "127.0.0.1 localhost"
        DATABASE_NAME: mysql
        DATABASE_USER: root
        DATABASE_PASS: password
        DATABASE_HOST: 127.0.0.1
        DATABASE_PORT: ${{ job.services.mysql.ports[3306] }}
        STATIC_URL: '/copp163_coordinator/static/'
    - name: Run Tests
      run: |
        python manage.py test
      env: 
        SECRET_KEY: django-insecure-r(h1v3!t+qib4ky91s=-eaxd@6ze)t+emce)+dq1%fgo$*s%6!
        DEBUG: true
        ALLOWED_HOSTS: "127.0.0.1 localhost"
        DATABASE_NAME: mysql
        DATABASE_USER: root
        DATABASE_PASS: password
        DATABASE_HOST: 127.0.0.1
        DATABASE_PORT: ${{ job.services.mysql.ports[3306] }}
        STATIC_URL: '/copp163_coordinator/static/'
